/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.AiAvailableBalance;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * AI鉴定可用次数
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiAvailableBalanceRecord extends UpdatableRecordImpl<AiAvailableBalanceRecord> implements Record6<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1711381147;

    /**
     * Setter for <code>etrade_goods.ai_available_balance.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.ai_available_balance.kind_id</code>. 品类id，值取自接口返回
     */
    public void setKindId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.kind_id</code>. 品类id，值取自接口返回
     */
    public Integer getKindId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>etrade_goods.ai_available_balance.used_times</code>. 已调用次数
     */
    public void setUsedTimes(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.used_times</code>. 已调用次数
     */
    public Integer getUsedTimes() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>etrade_goods.ai_available_balance.available_times</code>. 可用次数
     */
    public void setAvailableTimes(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.available_times</code>. 可用次数
     */
    public Integer getAvailableTimes() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>etrade_goods.ai_available_balance.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>etrade_goods.ai_available_balance.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_available_balance.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.KIND_ID;
    }

    @Override
    public Field<Integer> field3() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.USED_TIMES;
    }

    @Override
    public Field<Integer> field4() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.AVAILABLE_TIMES;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return AiAvailableBalance.AI_AVAILABLE_BALANCE.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getKindId();
    }

    @Override
    public Integer component3() {
        return getUsedTimes();
    }

    @Override
    public Integer component4() {
        return getAvailableTimes();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getKindId();
    }

    @Override
    public Integer value3() {
        return getUsedTimes();
    }

    @Override
    public Integer value4() {
        return getAvailableTimes();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public AiAvailableBalanceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord value2(Integer value) {
        setKindId(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord value3(Integer value) {
        setUsedTimes(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord value4(Integer value) {
        setAvailableTimes(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public AiAvailableBalanceRecord values(Integer value1, Integer value2, Integer value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiAvailableBalanceRecord
     */
    public AiAvailableBalanceRecord() {
        super(AiAvailableBalance.AI_AVAILABLE_BALANCE);
    }

    /**
     * Create a detached, initialised AiAvailableBalanceRecord
     */
    public AiAvailableBalanceRecord(Integer id, Integer kindId, Integer usedTimes, Integer availableTimes, LocalDateTime created, LocalDateTime modified) {
        super(AiAvailableBalance.AI_AVAILABLE_BALANCE);

        set(0, id);
        set(1, kindId);
        set(2, usedTimes);
        set(3, availableTimes);
        set(4, created);
        set(5, modified);
    }
}
