/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.AiBrandList;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * AI鉴定品牌
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiBrandListRecord extends UpdatableRecordImpl<AiBrandListRecord> implements Record8<Integer, Integer, String, Byte, String, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1429131823;

    /**
     * Setter for <code>etrade_goods.ai_brand_list.id</code>. 品牌id，值取自接口返回
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.id</code>. 品牌id，值取自接口返回
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.kind_id</code>. 品类id
     */
    public void setKindId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.kind_id</code>. 品类id
     */
    public Integer getKindId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.name</code>. 品牌名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.name</code>. 品牌名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.is_related</code>. 是否关联鉴定点（若为true，则该品牌直接跳转至鉴定点信息）
     */
    public void setIsRelated(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.is_related</code>. 是否关联鉴定点（若为true，则该品牌直接跳转至鉴定点信息）
     */
    public Byte getIsRelated() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.example_img</code>. 品牌示意图
     */
    public void setExampleImg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.example_img</code>. 品牌示意图
     */
    public String getExampleImg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.is_show</code>. 是否展示
     */
    public void setIsShow(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.is_show</code>. 是否展示
     */
    public Byte getIsShow() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>etrade_goods.ai_brand_list.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_brand_list.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, Byte, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, Byte, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AiBrandList.AI_BRAND_LIST.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AiBrandList.AI_BRAND_LIST.KIND_ID;
    }

    @Override
    public Field<String> field3() {
        return AiBrandList.AI_BRAND_LIST.NAME;
    }

    @Override
    public Field<Byte> field4() {
        return AiBrandList.AI_BRAND_LIST.IS_RELATED;
    }

    @Override
    public Field<String> field5() {
        return AiBrandList.AI_BRAND_LIST.EXAMPLE_IMG;
    }

    @Override
    public Field<Byte> field6() {
        return AiBrandList.AI_BRAND_LIST.IS_SHOW;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return AiBrandList.AI_BRAND_LIST.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return AiBrandList.AI_BRAND_LIST.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getKindId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Byte component4() {
        return getIsRelated();
    }

    @Override
    public String component5() {
        return getExampleImg();
    }

    @Override
    public Byte component6() {
        return getIsShow();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getKindId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Byte value4() {
        return getIsRelated();
    }

    @Override
    public String value5() {
        return getExampleImg();
    }

    @Override
    public Byte value6() {
        return getIsShow();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public AiBrandListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AiBrandListRecord value2(Integer value) {
        setKindId(value);
        return this;
    }

    @Override
    public AiBrandListRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AiBrandListRecord value4(Byte value) {
        setIsRelated(value);
        return this;
    }

    @Override
    public AiBrandListRecord value5(String value) {
        setExampleImg(value);
        return this;
    }

    @Override
    public AiBrandListRecord value6(Byte value) {
        setIsShow(value);
        return this;
    }

    @Override
    public AiBrandListRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public AiBrandListRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public AiBrandListRecord values(Integer value1, Integer value2, String value3, Byte value4, String value5, Byte value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiBrandListRecord
     */
    public AiBrandListRecord() {
        super(AiBrandList.AI_BRAND_LIST);
    }

    /**
     * Create a detached, initialised AiBrandListRecord
     */
    public AiBrandListRecord(Integer id, Integer kindId, String name, Byte isRelated, String exampleImg, Byte isShow, LocalDateTime created, LocalDateTime modified) {
        super(AiBrandList.AI_BRAND_LIST);

        set(0, id);
        set(1, kindId);
        set(2, name);
        set(3, isRelated);
        set(4, exampleImg);
        set(5, isShow);
        set(6, created);
        set(7, modified);
    }
}
