/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.AiKindList;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * AI鉴定品类
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiKindListRecord extends TableRecordImpl<AiKindListRecord> implements Record8<Integer, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1671466661;

    /**
     * Setter for <code>etrade_goods.ai_kind_list.id</code>. 品类id，值取自接口返回
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.id</code>. 品类id，值取自接口返回
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.name</code>. 品类中文名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.name</code>. 品类中文名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.is_related</code>. 是否关联鉴定点（若为true，则该品类直接跳转至鉴定点信息）
     */
    public void setIsRelated(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.is_related</code>. 是否关联鉴定点（若为true，则该品类直接跳转至鉴定点信息）
     */
    public Byte getIsRelated() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.example_img</code>. 品类示意图
     */
    public void setExampleImg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.example_img</code>. 品类示意图
     */
    public String getExampleImg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.is_show</code>. 是否展示
     */
    public void setIsShow(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.is_show</code>. 是否展示
     */
    public Byte getIsShow() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.lang</code>. 语言
     */
    public void setLang(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.lang</code>. 语言
     */
    public String getLang() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>etrade_goods.ai_kind_list.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.ai_kind_list.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AiKindList.AI_KIND_LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return AiKindList.AI_KIND_LIST.NAME;
    }

    @Override
    public Field<Byte> field3() {
        return AiKindList.AI_KIND_LIST.IS_RELATED;
    }

    @Override
    public Field<String> field4() {
        return AiKindList.AI_KIND_LIST.EXAMPLE_IMG;
    }

    @Override
    public Field<Byte> field5() {
        return AiKindList.AI_KIND_LIST.IS_SHOW;
    }

    @Override
    public Field<String> field6() {
        return AiKindList.AI_KIND_LIST.LANG;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return AiKindList.AI_KIND_LIST.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return AiKindList.AI_KIND_LIST.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Byte component3() {
        return getIsRelated();
    }

    @Override
    public String component4() {
        return getExampleImg();
    }

    @Override
    public Byte component5() {
        return getIsShow();
    }

    @Override
    public String component6() {
        return getLang();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Byte value3() {
        return getIsRelated();
    }

    @Override
    public String value4() {
        return getExampleImg();
    }

    @Override
    public Byte value5() {
        return getIsShow();
    }

    @Override
    public String value6() {
        return getLang();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public AiKindListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AiKindListRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AiKindListRecord value3(Byte value) {
        setIsRelated(value);
        return this;
    }

    @Override
    public AiKindListRecord value4(String value) {
        setExampleImg(value);
        return this;
    }

    @Override
    public AiKindListRecord value5(Byte value) {
        setIsShow(value);
        return this;
    }

    @Override
    public AiKindListRecord value6(String value) {
        setLang(value);
        return this;
    }

    @Override
    public AiKindListRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public AiKindListRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public AiKindListRecord values(Integer value1, String value2, Byte value3, String value4, Byte value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiKindListRecord
     */
    public AiKindListRecord() {
        super(AiKindList.AI_KIND_LIST);
    }

    /**
     * Create a detached, initialised AiKindListRecord
     */
    public AiKindListRecord(Integer id, String name, Byte isRelated, String exampleImg, Byte isShow, String lang, LocalDateTime created, LocalDateTime modified) {
        super(AiKindList.AI_KIND_LIST);

        set(0, id);
        set(1, name);
        set(2, isRelated);
        set(3, exampleImg);
        set(4, isShow);
        set(5, lang);
        set(6, created);
        set(7, modified);
    }
}
