/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GoodsTrade;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 商品交易
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsTradeRecord extends UpdatableRecordImpl<GoodsTradeRecord> {

    private static final long serialVersionUID = -1498502283;

    /**
     * Setter for <code>etrade_goods.goods_trade.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trade_no</code>. 订单编号
     */
    public void setTradeNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trade_no</code>. 订单编号
     */
    public String getTradeNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.title</code>. 支付标题
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.title</code>. 支付标题
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.goods_id</code>. 商品id
     */
    public void setGoodsId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.goods_id</code>. 商品id
     */
    public Long getGoodsId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.customer_id</code>. 买家用户id
     */
    public void setCustomerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.customer_id</code>. 买家用户id
     */
    public Long getCustomerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.customer</code>. 买家昵称
     */
    public void setCustomer(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.customer</code>. 买家昵称
     */
    public String getCustomer() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.seller_id</code>. 卖家用户id
     */
    public void setSellerId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.seller_id</code>. 卖家用户id
     */
    public Long getSellerId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trading_price</code>. 商品成交金额，不包括额外的运费
     */
    public void setTradingPrice(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trading_price</code>. 商品成交金额，不包括额外的运费
     */
    public BigDecimal getTradingPrice() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trading_time</code>. 开单时间
     */
    public void setTradingTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trading_time</code>. 开单时间
     */
    public LocalDateTime getTradingTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.state</code>. 交易状态：Pending payment、Payment failed、Completed 等等
     */
    public void setState(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.state</code>. 交易状态：Pending payment、Payment failed、Completed 等等
     */
    public String getState() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.shipping_method</code>. 交易方式：1面交 2快递 4当日达 等等
     */
    public void setShippingMethod(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.shipping_method</code>. 交易方式：1面交 2快递 4当日达 等等
     */
    public Integer getShippingMethod() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.other_fees</code>. 邮寄费用、AI检测费用等额外费用
     */
    public void setOtherFees(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.other_fees</code>. 邮寄费用、AI检测费用等额外费用
     */
    public BigDecimal getOtherFees() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.tax</code>. 商品税，或者叫佣金，系统所得费用
     */
    public void setTax(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.tax</code>. 商品税，或者叫佣金，系统所得费用
     */
    public BigDecimal getTax() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.subtotal</code>. 商家所得费用，如商品费用
     */
    public void setSubtotal(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.subtotal</code>. 商家所得费用，如商品费用
     */
    public BigDecimal getSubtotal() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.payment_method_id</code>. 买家支付方式
     */
    public void setPaymentMethodId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.payment_method_id</code>. 买家支付方式
     */
    public String getPaymentMethodId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.payment_type</code>. 买家支付类型
     */
    public void setPaymentType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.payment_type</code>. 买家支付类型
     */
    public String getPaymentType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.delivery_address_id</code>. 收货地址id
     */
    public void setDeliveryAddressId(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.delivery_address_id</code>. 收货地址id
     */
    public Integer getDeliveryAddressId() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.billing_address_id</code>. 账单地址id
     */
    public void setBillingAddressId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.billing_address_id</code>. 账单地址id
     */
    public Integer getBillingAddressId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.is_same_as_delivery_address</code>. 当账单地址同收货地址时，账单地址id为0
     */
    public void setIsSameAsDeliveryAddress(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.is_same_as_delivery_address</code>. 当账单地址同收货地址时，账单地址id为0
     */
    public Byte getIsSameAsDeliveryAddress() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.invoice_id</code>. 支付成功后发票id
     */
    public void setInvoiceId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.invoice_id</code>. 支付成功后发票id
     */
    public String getInvoiceId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.payment_card_id</code>. 如果付款方式是card，支付卡号id
     */
    public void setPaymentCardId(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.payment_card_id</code>. 如果付款方式是card，支付卡号id
     */
    public Integer getPaymentCardId() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsTradeRecord
     */
    public GoodsTradeRecord() {
        super(GoodsTrade.GOODS_TRADE);
    }

    /**
     * Create a detached, initialised GoodsTradeRecord
     */
    public GoodsTradeRecord(Long id, String tradeNo, String title, Long goodsId, Long customerId, String customer, Long sellerId, BigDecimal tradingPrice, LocalDateTime tradingTime, String state, Integer shippingMethod, BigDecimal otherFees, BigDecimal tax, BigDecimal subtotal, String paymentMethodId, String paymentType, Integer deliveryAddressId, Integer billingAddressId, Byte isSameAsDeliveryAddress, String invoiceId, Integer paymentCardId, LocalDateTime created, LocalDateTime modified) {
        super(GoodsTrade.GOODS_TRADE);

        set(0, id);
        set(1, tradeNo);
        set(2, title);
        set(3, goodsId);
        set(4, customerId);
        set(5, customer);
        set(6, sellerId);
        set(7, tradingPrice);
        set(8, tradingTime);
        set(9, state);
        set(10, shippingMethod);
        set(11, otherFees);
        set(12, tax);
        set(13, subtotal);
        set(14, paymentMethodId);
        set(15, paymentType);
        set(16, deliveryAddressId);
        set(17, billingAddressId);
        set(18, isSameAsDeliveryAddress);
        set(19, invoiceId);
        set(20, paymentCardId);
        set(21, created);
        set(22, modified);
    }
}
