/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GoodsTrade;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 商品交易
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsTradeRecord extends UpdatableRecordImpl<GoodsTradeRecord> implements Record13<Long, String, Long, Long, String, Long, BigDecimal, LocalDateTime, String, String, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 602018714;

    /**
     * Setter for <code>etrade_goods.goods_trade.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trade_no</code>. 订单编号
     */
    public void setTradeNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trade_no</code>. 订单编号
     */
    public String getTradeNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.goods_id</code>. 商品id
     */
    public void setGoodsId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.goods_id</code>. 商品id
     */
    public Long getGoodsId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.customer_id</code>. 买家id
     */
    public void setCustomerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.customer_id</code>. 买家id
     */
    public Long getCustomerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.customer</code>. 买家昵称
     */
    public void setCustomer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.customer</code>. 买家昵称
     */
    public String getCustomer() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.seller_id</code>. 卖家id
     */
    public void setSellerId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.seller_id</code>. 卖家id
     */
    public Long getSellerId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trading_price</code>. 成交金额，不包括额外的运费
     */
    public void setTradingPrice(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trading_price</code>. 成交金额，不包括额外的运费
     */
    public BigDecimal getTradingPrice() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.trading_time</code>. 成交时间
     */
    public void setTradingTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.trading_time</code>. 成交时间
     */
    public LocalDateTime getTradingTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.state</code>. 交易状态：1待付款 2交易完成 等等
     */
    public void setState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.state</code>. 交易状态：1待付款 2交易完成 等等
     */
    public String getState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.delivery_type</code>. 发货方式：1邮寄 2面交 等等
     */
    public void setDeliveryType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.delivery_type</code>. 发货方式：1邮寄 2面交 等等
     */
    public String getDeliveryType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.post_price</code>. 如果是邮寄方式发货，邮费金额
     */
    public void setPostPrice(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.post_price</code>. 如果是邮寄方式发货，邮费金额
     */
    public BigDecimal getPostPrice() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>etrade_goods.goods_trade.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.goods_trade.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, Long, Long, String, Long, BigDecimal, LocalDateTime, String, String, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, Long, Long, String, Long, BigDecimal, LocalDateTime, String, String, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GoodsTrade.GOODS_TRADE.ID;
    }

    @Override
    public Field<String> field2() {
        return GoodsTrade.GOODS_TRADE.TRADE_NO;
    }

    @Override
    public Field<Long> field3() {
        return GoodsTrade.GOODS_TRADE.GOODS_ID;
    }

    @Override
    public Field<Long> field4() {
        return GoodsTrade.GOODS_TRADE.CUSTOMER_ID;
    }

    @Override
    public Field<String> field5() {
        return GoodsTrade.GOODS_TRADE.CUSTOMER;
    }

    @Override
    public Field<Long> field6() {
        return GoodsTrade.GOODS_TRADE.SELLER_ID;
    }

    @Override
    public Field<BigDecimal> field7() {
        return GoodsTrade.GOODS_TRADE.TRADING_PRICE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return GoodsTrade.GOODS_TRADE.TRADING_TIME;
    }

    @Override
    public Field<String> field9() {
        return GoodsTrade.GOODS_TRADE.STATE;
    }

    @Override
    public Field<String> field10() {
        return GoodsTrade.GOODS_TRADE.DELIVERY_TYPE;
    }

    @Override
    public Field<BigDecimal> field11() {
        return GoodsTrade.GOODS_TRADE.POST_PRICE;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return GoodsTrade.GOODS_TRADE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return GoodsTrade.GOODS_TRADE.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTradeNo();
    }

    @Override
    public Long component3() {
        return getGoodsId();
    }

    @Override
    public Long component4() {
        return getCustomerId();
    }

    @Override
    public String component5() {
        return getCustomer();
    }

    @Override
    public Long component6() {
        return getSellerId();
    }

    @Override
    public BigDecimal component7() {
        return getTradingPrice();
    }

    @Override
    public LocalDateTime component8() {
        return getTradingTime();
    }

    @Override
    public String component9() {
        return getState();
    }

    @Override
    public String component10() {
        return getDeliveryType();
    }

    @Override
    public BigDecimal component11() {
        return getPostPrice();
    }

    @Override
    public LocalDateTime component12() {
        return getCreated();
    }

    @Override
    public LocalDateTime component13() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTradeNo();
    }

    @Override
    public Long value3() {
        return getGoodsId();
    }

    @Override
    public Long value4() {
        return getCustomerId();
    }

    @Override
    public String value5() {
        return getCustomer();
    }

    @Override
    public Long value6() {
        return getSellerId();
    }

    @Override
    public BigDecimal value7() {
        return getTradingPrice();
    }

    @Override
    public LocalDateTime value8() {
        return getTradingTime();
    }

    @Override
    public String value9() {
        return getState();
    }

    @Override
    public String value10() {
        return getDeliveryType();
    }

    @Override
    public BigDecimal value11() {
        return getPostPrice();
    }

    @Override
    public LocalDateTime value12() {
        return getCreated();
    }

    @Override
    public LocalDateTime value13() {
        return getModified();
    }

    @Override
    public GoodsTradeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value2(String value) {
        setTradeNo(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value3(Long value) {
        setGoodsId(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value4(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value5(String value) {
        setCustomer(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value6(Long value) {
        setSellerId(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value7(BigDecimal value) {
        setTradingPrice(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value8(LocalDateTime value) {
        setTradingTime(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value9(String value) {
        setState(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value10(String value) {
        setDeliveryType(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value11(BigDecimal value) {
        setPostPrice(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value12(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GoodsTradeRecord value13(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GoodsTradeRecord values(Long value1, String value2, Long value3, Long value4, String value5, Long value6, BigDecimal value7, LocalDateTime value8, String value9, String value10, BigDecimal value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsTradeRecord
     */
    public GoodsTradeRecord() {
        super(GoodsTrade.GOODS_TRADE);
    }

    /**
     * Create a detached, initialised GoodsTradeRecord
     */
    public GoodsTradeRecord(Long id, String tradeNo, Long goodsId, Long customerId, String customer, Long sellerId, BigDecimal tradingPrice, LocalDateTime tradingTime, String state, String deliveryType, BigDecimal postPrice, LocalDateTime created, LocalDateTime modified) {
        super(GoodsTrade.GOODS_TRADE);

        set(0, id);
        set(1, tradeNo);
        set(2, goodsId);
        set(3, customerId);
        set(4, customer);
        set(5, sellerId);
        set(6, tradingPrice);
        set(7, tradingTime);
        set(8, state);
        set(9, deliveryType);
        set(10, postPrice);
        set(11, created);
        set(12, modified);
    }
}
