/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponCouponData;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购券数据
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponDataRecord extends UpdatableRecordImpl<GrouponCouponDataRecord> implements Record8<Long, Long, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1210106548;

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.browse_number</code>. 浏览次数
     */
    public void setBrowseNumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.browse_number</code>. 浏览次数
     */
    public Integer getBrowseNumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.like_number</code>. 收藏/喜欢次数
     */
    public void setLikeNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.like_number</code>. 收藏/喜欢次数
     */
    public Integer getLikeNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.comment_number</code>. 评论次数
     */
    public void setCommentNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.comment_number</code>. 评论次数
     */
    public Integer getCommentNumber() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.trade_number</code>. 订购次数
     */
    public void setTradeNumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.trade_number</code>. 订购次数
     */
    public Integer getTradeNumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_data.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_data.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GrouponCouponData.GROUPON_COUPON_DATA.ID;
    }

    @Override
    public Field<Long> field2() {
        return GrouponCouponData.GROUPON_COUPON_DATA.GROUPON_ID;
    }

    @Override
    public Field<Integer> field3() {
        return GrouponCouponData.GROUPON_COUPON_DATA.BROWSE_NUMBER;
    }

    @Override
    public Field<Integer> field4() {
        return GrouponCouponData.GROUPON_COUPON_DATA.LIKE_NUMBER;
    }

    @Override
    public Field<Integer> field5() {
        return GrouponCouponData.GROUPON_COUPON_DATA.COMMENT_NUMBER;
    }

    @Override
    public Field<Integer> field6() {
        return GrouponCouponData.GROUPON_COUPON_DATA.TRADE_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return GrouponCouponData.GROUPON_COUPON_DATA.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return GrouponCouponData.GROUPON_COUPON_DATA.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGrouponId();
    }

    @Override
    public Integer component3() {
        return getBrowseNumber();
    }

    @Override
    public Integer component4() {
        return getLikeNumber();
    }

    @Override
    public Integer component5() {
        return getCommentNumber();
    }

    @Override
    public Integer component6() {
        return getTradeNumber();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGrouponId();
    }

    @Override
    public Integer value3() {
        return getBrowseNumber();
    }

    @Override
    public Integer value4() {
        return getLikeNumber();
    }

    @Override
    public Integer value5() {
        return getCommentNumber();
    }

    @Override
    public Integer value6() {
        return getTradeNumber();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public GrouponCouponDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value2(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value3(Integer value) {
        setBrowseNumber(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value4(Integer value) {
        setLikeNumber(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value5(Integer value) {
        setCommentNumber(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value6(Integer value) {
        setTradeNumber(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GrouponCouponDataRecord values(Long value1, Long value2, Integer value3, Integer value4, Integer value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponCouponDataRecord
     */
    public GrouponCouponDataRecord() {
        super(GrouponCouponData.GROUPON_COUPON_DATA);
    }

    /**
     * Create a detached, initialised GrouponCouponDataRecord
     */
    public GrouponCouponDataRecord(Long id, Long grouponId, Integer browseNumber, Integer likeNumber, Integer commentNumber, Integer tradeNumber, LocalDateTime created, LocalDateTime modified) {
        super(GrouponCouponData.GROUPON_COUPON_DATA);

        set(0, id);
        set(1, grouponId);
        set(2, browseNumber);
        set(3, likeNumber);
        set(4, commentNumber);
        set(5, tradeNumber);
        set(6, created);
        set(7, modified);
    }
}
