/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponCouponPicture;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购券图片
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponPictureRecord extends UpdatableRecordImpl<GrouponCouponPictureRecord> implements Record9<Long, Long, String, String, String, Byte, Byte, LocalDateTime, Byte> {

    private static final long serialVersionUID = 1723415555;

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.url</code>. 对象存储地址
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.url</code>. 对象存储地址
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.key</code>. 对象存储key
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.key</code>. 对象存储key
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.version_id</code>. 对象存储版本号
     */
    public void setVersionId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.version_id</code>. 对象存储版本号
     */
    public String getVersionId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.is_main</code>. 是否商品主图：1是
     */
    public void setIsMain(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.is_main</code>. 是否商品主图：1是
     */
    public Byte getIsMain() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.deleted</code>. 是否弃用, 1 : 废弃，0 : 正常
     */
    public void setDeleted(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.deleted</code>. 是否弃用, 1 : 废弃，0 : 正常
     */
    public Byte getDeleted() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_picture.is_icon</code>. 是否是icon：值为1时是icon
     */
    public void setIsIcon(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_picture.is_icon</code>. 是否是icon：值为1时是icon
     */
    public Byte getIsIcon() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, Byte, Byte, LocalDateTime, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, String, Byte, Byte, LocalDateTime, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.ID;
    }

    @Override
    public Field<Long> field2() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.GROUPON_ID;
    }

    @Override
    public Field<String> field3() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.URL;
    }

    @Override
    public Field<String> field4() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.KEY;
    }

    @Override
    public Field<String> field5() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.VERSION_ID;
    }

    @Override
    public Field<Byte> field6() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.IS_MAIN;
    }

    @Override
    public Field<Byte> field7() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.DELETED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.CREATED;
    }

    @Override
    public Field<Byte> field9() {
        return GrouponCouponPicture.GROUPON_COUPON_PICTURE.IS_ICON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGrouponId();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String component4() {
        return getKey();
    }

    @Override
    public String component5() {
        return getVersionId();
    }

    @Override
    public Byte component6() {
        return getIsMain();
    }

    @Override
    public Byte component7() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component8() {
        return getCreated();
    }

    @Override
    public Byte component9() {
        return getIsIcon();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGrouponId();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public String value4() {
        return getKey();
    }

    @Override
    public String value5() {
        return getVersionId();
    }

    @Override
    public Byte value6() {
        return getIsMain();
    }

    @Override
    public Byte value7() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value8() {
        return getCreated();
    }

    @Override
    public Byte value9() {
        return getIsIcon();
    }

    @Override
    public GrouponCouponPictureRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value2(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value4(String value) {
        setKey(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value5(String value) {
        setVersionId(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value6(Byte value) {
        setIsMain(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value7(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value8(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord value9(Byte value) {
        setIsIcon(value);
        return this;
    }

    @Override
    public GrouponCouponPictureRecord values(Long value1, Long value2, String value3, String value4, String value5, Byte value6, Byte value7, LocalDateTime value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponCouponPictureRecord
     */
    public GrouponCouponPictureRecord() {
        super(GrouponCouponPicture.GROUPON_COUPON_PICTURE);
    }

    /**
     * Create a detached, initialised GrouponCouponPictureRecord
     */
    public GrouponCouponPictureRecord(Long id, Long grouponId, String url, String key, String versionId, Byte isMain, Byte deleted, LocalDateTime created, Byte isIcon) {
        super(GrouponCouponPicture.GROUPON_COUPON_PICTURE);

        set(0, id);
        set(1, grouponId);
        set(2, url);
        set(3, key);
        set(4, versionId);
        set(5, isMain);
        set(6, deleted);
        set(7, created);
        set(8, isIcon);
    }
}
