/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponCouponPlan;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购优惠券方案
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponPlanRecord extends UpdatableRecordImpl<GrouponCouponPlanRecord> implements Record8<Long, Long, Integer, BigDecimal, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 815144180;

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.plan_id</code>. 方案id, 展示效果:方案一 方案二等
     */
    public void setPlanId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.plan_id</code>. 方案id, 展示效果:方案一 方案二等
     */
    public Integer getPlanId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.price</code>. 价格
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.price</code>. 价格
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.price_interval</code>. 价格区间，EQ=; &gt;=GE; &lt;=LE
     */
    public void setPriceInterval(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.price_interval</code>. 价格区间，EQ=; &gt;=GE; &lt;=LE
     */
    public String getPriceInterval() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.text</code>. 方案详情
     */
    public void setText(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.text</code>. 方案详情
     */
    public String getText() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_plan.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_plan.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Integer, BigDecimal, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Integer, BigDecimal, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.ID;
    }

    @Override
    public Field<Long> field2() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.GROUPON_ID;
    }

    @Override
    public Field<Integer> field3() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.PLAN_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.PRICE;
    }

    @Override
    public Field<String> field5() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.PRICE_INTERVAL;
    }

    @Override
    public Field<String> field6() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.TEXT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return GrouponCouponPlan.GROUPON_COUPON_PLAN.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGrouponId();
    }

    @Override
    public Integer component3() {
        return getPlanId();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public String component5() {
        return getPriceInterval();
    }

    @Override
    public String component6() {
        return getText();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGrouponId();
    }

    @Override
    public Integer value3() {
        return getPlanId();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public String value5() {
        return getPriceInterval();
    }

    @Override
    public String value6() {
        return getText();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public GrouponCouponPlanRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value2(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value3(Integer value) {
        setPlanId(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value5(String value) {
        setPriceInterval(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value6(String value) {
        setText(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GrouponCouponPlanRecord values(Long value1, Long value2, Integer value3, BigDecimal value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponCouponPlanRecord
     */
    public GrouponCouponPlanRecord() {
        super(GrouponCouponPlan.GROUPON_COUPON_PLAN);
    }

    /**
     * Create a detached, initialised GrouponCouponPlanRecord
     */
    public GrouponCouponPlanRecord(Long id, Long grouponId, Integer planId, BigDecimal price, String priceInterval, String text, LocalDateTime created, LocalDateTime modified) {
        super(GrouponCouponPlan.GROUPON_COUPON_PLAN);

        set(0, id);
        set(1, grouponId);
        set(2, planId);
        set(3, price);
        set(4, priceInterval);
        set(5, text);
        set(6, created);
        set(7, modified);
    }
}
