/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponCouponDetail;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购优惠券商品说明
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponDetailRecord extends UpdatableRecordImpl<GrouponCouponDetailRecord> implements Record6<Long, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1397839387;

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.text</code>. 文案, 根据主键排序
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.text</code>. 文案, 根据主键排序
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.type</code>. 类别: 基本说明、使用声明等
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.type</code>. 类别: 基本说明、使用声明等
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_detail.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_detail.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.ID;
    }

    @Override
    public Field<Long> field2() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.GROUPON_ID;
    }

    @Override
    public Field<String> field3() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.TEXT;
    }

    @Override
    public Field<String> field4() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.TYPE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return GrouponCouponDetail.GROUPON_COUPON_DETAIL.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGrouponId();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGrouponId();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public GrouponCouponDetailRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord value2(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GrouponCouponDetailRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponCouponDetailRecord
     */
    public GrouponCouponDetailRecord() {
        super(GrouponCouponDetail.GROUPON_COUPON_DETAIL);
    }

    /**
     * Create a detached, initialised GrouponCouponDetailRecord
     */
    public GrouponCouponDetailRecord(Long id, Long grouponId, String text, String type, LocalDateTime created, LocalDateTime modified) {
        super(GrouponCouponDetail.GROUPON_COUPON_DETAIL);

        set(0, id);
        set(1, grouponId);
        set(2, text);
        set(3, type);
        set(4, created);
        set(5, modified);
    }
}
