/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponClass;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购分类
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponClassRecord extends UpdatableRecordImpl<GrouponClassRecord> implements Record7<Integer, String, String, Byte, LocalDateTime, LocalDateTime, Long> {

    private static final long serialVersionUID = 343444996;

    /**
     * Setter for <code>etrade_goods.groupon_class.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.class_name</code>. 级别名称
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.class_name</code>. 级别名称
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.class_path</code>. 级别path,用于搜索,例如衣服id为1,衣服下的二级T恤id为14,则T恤path为1:14
     */
    public void setClassPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.class_path</code>. 级别path,用于搜索,例如衣服id为1,衣服下的二级T恤id为14,则T恤path为1:14
     */
    public String getClassPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.class_level</code>. 级别,从1到n,数字越大分类越精细
     */
    public void setClassLevel(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.class_level</code>. 级别,从1到n,数字越大分类越精细
     */
    public Byte getClassLevel() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>etrade_goods.groupon_class.icon_id</code>. icon
     */
    public void setIconId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_class.icon_id</code>. icon
     */
    public Long getIconId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Byte, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Byte, LocalDateTime, LocalDateTime, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GrouponClass.GROUPON_CLASS.ID;
    }

    @Override
    public Field<String> field2() {
        return GrouponClass.GROUPON_CLASS.CLASS_NAME;
    }

    @Override
    public Field<String> field3() {
        return GrouponClass.GROUPON_CLASS.CLASS_PATH;
    }

    @Override
    public Field<Byte> field4() {
        return GrouponClass.GROUPON_CLASS.CLASS_LEVEL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return GrouponClass.GROUPON_CLASS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return GrouponClass.GROUPON_CLASS.MODIFIED;
    }

    @Override
    public Field<Long> field7() {
        return GrouponClass.GROUPON_CLASS.ICON_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClassName();
    }

    @Override
    public String component3() {
        return getClassPath();
    }

    @Override
    public Byte component4() {
        return getClassLevel();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Long component7() {
        return getIconId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClassName();
    }

    @Override
    public String value3() {
        return getClassPath();
    }

    @Override
    public Byte value4() {
        return getClassLevel();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public Long value7() {
        return getIconId();
    }

    @Override
    public GrouponClassRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponClassRecord value2(String value) {
        setClassName(value);
        return this;
    }

    @Override
    public GrouponClassRecord value3(String value) {
        setClassPath(value);
        return this;
    }

    @Override
    public GrouponClassRecord value4(Byte value) {
        setClassLevel(value);
        return this;
    }

    @Override
    public GrouponClassRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponClassRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GrouponClassRecord value7(Long value) {
        setIconId(value);
        return this;
    }

    @Override
    public GrouponClassRecord values(Integer value1, String value2, String value3, Byte value4, LocalDateTime value5, LocalDateTime value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponClassRecord
     */
    public GrouponClassRecord() {
        super(GrouponClass.GROUPON_CLASS);
    }

    /**
     * Create a detached, initialised GrouponClassRecord
     */
    public GrouponClassRecord(Integer id, String className, String classPath, Byte classLevel, LocalDateTime created, LocalDateTime modified, Long iconId) {
        super(GrouponClass.GROUPON_CLASS);

        set(0, id);
        set(1, className);
        set(2, classPath);
        set(3, classLevel);
        set(4, created);
        set(5, modified);
        set(6, iconId);
    }
}
