/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.GrouponCouponRule;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团购优惠券使用规则
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponRuleRecord extends UpdatableRecordImpl<GrouponCouponRuleRecord> implements Record16<Long, Long, String, String, String, String, Byte, Byte, String, String, String, String, Integer, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1366274476;

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.service_time_interval</code>. 有效时间区间：&lt;= and &lt;=BETWEEN; &gt;=GE; &lt;=LE
     */
    public void setServiceTimeInterval(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.service_time_interval</code>. 有效时间区间：&lt;= and &lt;=BETWEEN; &gt;=GE; &lt;=LE
     */
    public String getServiceTimeInterval() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.service_time_unit</code>. 有效时间单位: DATE; WEEK
     */
    public void setServiceTimeUnit(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.service_time_unit</code>. 有效时间单位: DATE; WEEK
     */
    public String getServiceTimeUnit() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.service_time_start</code>. 有效时间开始
     */
    public void setServiceTimeStart(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.service_time_start</code>. 有效时间开始
     */
    public String getServiceTimeStart() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.service_time_end</code>. 有效时间截止
     */
    public void setServiceTimeEnd(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.service_time_end</code>. 有效时间截止
     */
    public String getServiceTimeEnd() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.min_reply_hours</code>. 最小回复时间
     */
    public void setMinReplyHours(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.min_reply_hours</code>. 最小回复时间
     */
    public Byte getMinReplyHours() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.is_allow_cancel</code>. 是否允许取消, 值为1时允许
     */
    public void setIsAllowCancel(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.is_allow_cancel</code>. 是否允许取消, 值为1时允许
     */
    public Byte getIsAllowCancel() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.applicable_brand</code>. 适用的品牌
     */
    public void setApplicableBrand(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.applicable_brand</code>. 适用的品牌
     */
    public String getApplicableBrand() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.applicable_shop</code>. 适用的门店
     */
    public void setApplicableShop(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.applicable_shop</code>. 适用的门店
     */
    public String getApplicableShop() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.shop_address</code>. 适用门店地址
     */
    public void setShopAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.shop_address</code>. 适用门店地址
     */
    public String getShopAddress() {
        return (String) get(10);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.shop_arrival_method</code>. 门店到达方式
     */
    public void setShopArrivalMethod(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.shop_arrival_method</code>. 门店到达方式
     */
    public String getShopArrivalMethod() {
        return (String) get(11);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.limit_number</code>. 限制订购数量
     */
    public void setLimitNumber(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.limit_number</code>. 限制订购数量
     */
    public Integer getLimitNumber() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>etrade_goods.groupon_coupon_rule.effective_days</code>. 有效天数
     */
    public void setEffectiveDays(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>etrade_goods.groupon_coupon_rule.effective_days</code>. 有效天数
     */
    public Integer getEffectiveDays() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, String, String, String, String, Byte, Byte, String, String, String, String, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, Long, String, String, String, String, Byte, Byte, String, String, String, String, Integer, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.ID;
    }

    @Override
    public Field<Long> field2() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.GROUPON_ID;
    }

    @Override
    public Field<String> field3() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SERVICE_TIME_INTERVAL;
    }

    @Override
    public Field<String> field4() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SERVICE_TIME_UNIT;
    }

    @Override
    public Field<String> field5() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SERVICE_TIME_START;
    }

    @Override
    public Field<String> field6() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SERVICE_TIME_END;
    }

    @Override
    public Field<Byte> field7() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.MIN_REPLY_HOURS;
    }

    @Override
    public Field<Byte> field8() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.IS_ALLOW_CANCEL;
    }

    @Override
    public Field<String> field9() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.APPLICABLE_BRAND;
    }

    @Override
    public Field<String> field10() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.APPLICABLE_SHOP;
    }

    @Override
    public Field<String> field11() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SHOP_ADDRESS;
    }

    @Override
    public Field<String> field12() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.SHOP_ARRIVAL_METHOD;
    }

    @Override
    public Field<Integer> field13() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.LIMIT_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.MODIFIED;
    }

    @Override
    public Field<Integer> field16() {
        return GrouponCouponRule.GROUPON_COUPON_RULE.EFFECTIVE_DAYS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGrouponId();
    }

    @Override
    public String component3() {
        return getServiceTimeInterval();
    }

    @Override
    public String component4() {
        return getServiceTimeUnit();
    }

    @Override
    public String component5() {
        return getServiceTimeStart();
    }

    @Override
    public String component6() {
        return getServiceTimeEnd();
    }

    @Override
    public Byte component7() {
        return getMinReplyHours();
    }

    @Override
    public Byte component8() {
        return getIsAllowCancel();
    }

    @Override
    public String component9() {
        return getApplicableBrand();
    }

    @Override
    public String component10() {
        return getApplicableShop();
    }

    @Override
    public String component11() {
        return getShopAddress();
    }

    @Override
    public String component12() {
        return getShopArrivalMethod();
    }

    @Override
    public Integer component13() {
        return getLimitNumber();
    }

    @Override
    public LocalDateTime component14() {
        return getCreated();
    }

    @Override
    public LocalDateTime component15() {
        return getModified();
    }

    @Override
    public Integer component16() {
        return getEffectiveDays();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGrouponId();
    }

    @Override
    public String value3() {
        return getServiceTimeInterval();
    }

    @Override
    public String value4() {
        return getServiceTimeUnit();
    }

    @Override
    public String value5() {
        return getServiceTimeStart();
    }

    @Override
    public String value6() {
        return getServiceTimeEnd();
    }

    @Override
    public Byte value7() {
        return getMinReplyHours();
    }

    @Override
    public Byte value8() {
        return getIsAllowCancel();
    }

    @Override
    public String value9() {
        return getApplicableBrand();
    }

    @Override
    public String value10() {
        return getApplicableShop();
    }

    @Override
    public String value11() {
        return getShopAddress();
    }

    @Override
    public String value12() {
        return getShopArrivalMethod();
    }

    @Override
    public Integer value13() {
        return getLimitNumber();
    }

    @Override
    public LocalDateTime value14() {
        return getCreated();
    }

    @Override
    public LocalDateTime value15() {
        return getModified();
    }

    @Override
    public Integer value16() {
        return getEffectiveDays();
    }

    @Override
    public GrouponCouponRuleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value2(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value3(String value) {
        setServiceTimeInterval(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value4(String value) {
        setServiceTimeUnit(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value5(String value) {
        setServiceTimeStart(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value6(String value) {
        setServiceTimeEnd(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value7(Byte value) {
        setMinReplyHours(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value8(Byte value) {
        setIsAllowCancel(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value9(String value) {
        setApplicableBrand(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value10(String value) {
        setApplicableShop(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value11(String value) {
        setShopAddress(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value12(String value) {
        setShopArrivalMethod(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value13(Integer value) {
        setLimitNumber(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value14(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value15(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord value16(Integer value) {
        setEffectiveDays(value);
        return this;
    }

    @Override
    public GrouponCouponRuleRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Byte value7, Byte value8, String value9, String value10, String value11, String value12, Integer value13, LocalDateTime value14, LocalDateTime value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrouponCouponRuleRecord
     */
    public GrouponCouponRuleRecord() {
        super(GrouponCouponRule.GROUPON_COUPON_RULE);
    }

    /**
     * Create a detached, initialised GrouponCouponRuleRecord
     */
    public GrouponCouponRuleRecord(Long id, Long grouponId, String serviceTimeInterval, String serviceTimeUnit, String serviceTimeStart, String serviceTimeEnd, Byte minReplyHours, Byte isAllowCancel, String applicableBrand, String applicableShop, String shopAddress, String shopArrivalMethod, Integer limitNumber, LocalDateTime created, LocalDateTime modified, Integer effectiveDays) {
        super(GrouponCouponRule.GROUPON_COUPON_RULE);

        set(0, id);
        set(1, grouponId);
        set(2, serviceTimeInterval);
        set(3, serviceTimeUnit);
        set(4, serviceTimeStart);
        set(5, serviceTimeEnd);
        set(6, minReplyHours);
        set(7, isAllowCancel);
        set(8, applicableBrand);
        set(9, applicableShop);
        set(10, shopAddress);
        set(11, shopArrivalMethod);
        set(12, limitNumber);
        set(13, created);
        set(14, modified);
        set(15, effectiveDays);
    }
}
