/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.PaymentCard;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * 买家信用卡/借记卡信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentCardRecord extends TableRecordImpl<PaymentCardRecord> implements Record12<Integer, Long, String, String, String, String, String, Byte, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 500297863;

    /**
     * Setter for <code>etrade_goods.payment_card.id</code>. 主键id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.id</code>. 主键id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.user_id</code>. 系统用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.user_id</code>. 系统用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.card_number</code>. 卡号
     */
    public void setCardNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.card_number</code>. 卡号
     */
    public String getCardNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.expire_year</code>. 到期年份，格式:MM，比如：26
     */
    public void setExpireYear(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.expire_year</code>. 到期年份，格式:MM，比如：26
     */
    public String getExpireYear() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.expire_month</code>. 到期月份，格式:YY，比如：01
     */
    public void setExpireMonth(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.expire_month</code>. 到期月份，格式:YY，比如：01
     */
    public String getExpireMonth() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.cvs</code>. 信用卡验证码
     */
    public void setCvs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.cvs</code>. 信用卡验证码
     */
    public String getCvs() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.title</code>. 信用卡标记
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.title</code>. 信用卡标记
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.is_default</code>. 是否是默认卡
     */
    public void setIsDefault(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.is_default</code>. 是否是默认卡
     */
    public Byte getIsDefault() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.brand</code>. 信用卡品牌，比如：Visa、MasterCard、American Express (Amex)、Discover等
     */
    public void setBrand(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.brand</code>. 信用卡品牌，比如：Visa、MasterCard、American Express (Amex)、Discover等
     */
    public String getBrand() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.type</code>. 卡类型：credit/debit
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.type</code>. 卡类型：credit/debit
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>etrade_goods.payment_card.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_card.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Long, String, String, String, String, String, Byte, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Long, String, String, String, String, String, Byte, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PaymentCard.PAYMENT_CARD.ID;
    }

    @Override
    public Field<Long> field2() {
        return PaymentCard.PAYMENT_CARD.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return PaymentCard.PAYMENT_CARD.CARD_NUMBER;
    }

    @Override
    public Field<String> field4() {
        return PaymentCard.PAYMENT_CARD.EXPIRE_YEAR;
    }

    @Override
    public Field<String> field5() {
        return PaymentCard.PAYMENT_CARD.EXPIRE_MONTH;
    }

    @Override
    public Field<String> field6() {
        return PaymentCard.PAYMENT_CARD.CVS;
    }

    @Override
    public Field<String> field7() {
        return PaymentCard.PAYMENT_CARD.TITLE;
    }

    @Override
    public Field<Byte> field8() {
        return PaymentCard.PAYMENT_CARD.IS_DEFAULT;
    }

    @Override
    public Field<String> field9() {
        return PaymentCard.PAYMENT_CARD.BRAND;
    }

    @Override
    public Field<String> field10() {
        return PaymentCard.PAYMENT_CARD.TYPE;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return PaymentCard.PAYMENT_CARD.CREATED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return PaymentCard.PAYMENT_CARD.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getCardNumber();
    }

    @Override
    public String component4() {
        return getExpireYear();
    }

    @Override
    public String component5() {
        return getExpireMonth();
    }

    @Override
    public String component6() {
        return getCvs();
    }

    @Override
    public String component7() {
        return getTitle();
    }

    @Override
    public Byte component8() {
        return getIsDefault();
    }

    @Override
    public String component9() {
        return getBrand();
    }

    @Override
    public String component10() {
        return getType();
    }

    @Override
    public LocalDateTime component11() {
        return getCreated();
    }

    @Override
    public LocalDateTime component12() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getCardNumber();
    }

    @Override
    public String value4() {
        return getExpireYear();
    }

    @Override
    public String value5() {
        return getExpireMonth();
    }

    @Override
    public String value6() {
        return getCvs();
    }

    @Override
    public String value7() {
        return getTitle();
    }

    @Override
    public Byte value8() {
        return getIsDefault();
    }

    @Override
    public String value9() {
        return getBrand();
    }

    @Override
    public String value10() {
        return getType();
    }

    @Override
    public LocalDateTime value11() {
        return getCreated();
    }

    @Override
    public LocalDateTime value12() {
        return getModified();
    }

    @Override
    public PaymentCardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PaymentCardRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public PaymentCardRecord value3(String value) {
        setCardNumber(value);
        return this;
    }

    @Override
    public PaymentCardRecord value4(String value) {
        setExpireYear(value);
        return this;
    }

    @Override
    public PaymentCardRecord value5(String value) {
        setExpireMonth(value);
        return this;
    }

    @Override
    public PaymentCardRecord value6(String value) {
        setCvs(value);
        return this;
    }

    @Override
    public PaymentCardRecord value7(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PaymentCardRecord value8(Byte value) {
        setIsDefault(value);
        return this;
    }

    @Override
    public PaymentCardRecord value9(String value) {
        setBrand(value);
        return this;
    }

    @Override
    public PaymentCardRecord value10(String value) {
        setType(value);
        return this;
    }

    @Override
    public PaymentCardRecord value11(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public PaymentCardRecord value12(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public PaymentCardRecord values(Integer value1, Long value2, String value3, String value4, String value5, String value6, String value7, Byte value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentCardRecord
     */
    public PaymentCardRecord() {
        super(PaymentCard.PAYMENT_CARD);
    }

    /**
     * Create a detached, initialised PaymentCardRecord
     */
    public PaymentCardRecord(Integer id, Long userId, String cardNumber, String expireYear, String expireMonth, String cvs, String title, Byte isDefault, String brand, String type, LocalDateTime created, LocalDateTime modified) {
        super(PaymentCard.PAYMENT_CARD);

        set(0, id);
        set(1, userId);
        set(2, cardNumber);
        set(3, expireYear);
        set(4, expireMonth);
        set(5, cvs);
        set(6, title);
        set(7, isDefault);
        set(8, brand);
        set(9, type);
        set(10, created);
        set(11, modified);
    }
}
