/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.PaymentRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * 支付记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecordRecord extends TableRecordImpl<PaymentRecordRecord> implements Record12<Long, String, Long, Integer, Integer, Byte, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -954985819;

    /**
     * Setter for <code>etrade_goods.payment_record.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.transaction_no</code>. 交易单号
     */
    public void setTransactionNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.transaction_no</code>. 交易单号
     */
    public String getTransactionNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.user_id</code>. 系统用户id
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.user_id</code>. 系统用户id
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.delivery_address_id</code>. 用户收货地址id
     */
    public void setDeliveryAddressId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.delivery_address_id</code>. 用户收货地址id
     */
    public Integer getDeliveryAddressId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.billing_address_id</code>. 用户账单地址id，仅当支付方式为信用卡时有效
     */
    public void setBillingAddressId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.billing_address_id</code>. 用户账单地址id，仅当支付方式为信用卡时有效
     */
    public Integer getBillingAddressId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.is_same_as_delivery_address</code>. 是否使用收货地址作为账单地址，如果是则billing_address_id不生效
     */
    public void setIsSameAsDeliveryAddress(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.is_same_as_delivery_address</code>. 是否使用收货地址作为账单地址，如果是则billing_address_id不生效
     */
    public Byte getIsSameAsDeliveryAddress() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.shipping_method</code>. 交易方式：Public Meetup、Standard Shipping、Same-day Delivery..
     */
    public void setShippingMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.shipping_method</code>. 交易方式：Public Meetup、Standard Shipping、Same-day Delivery..
     */
    public String getShippingMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.payment_type</code>. 支付类型，比如：card、alipay、wechat、google_pay、apple_pay
     */
    public void setPaymentType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.payment_type</code>. 支付类型，比如：card、alipay、wechat、google_pay、apple_pay
     */
    public String getPaymentType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.payment_method_id</code>.
     */
    public void setPaymentMethodId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.payment_method_id</code>.
     */
    public String getPaymentMethodId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.token</code>.
     */
    public void setToken(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.token</code>.
     */
    public String getToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>etrade_goods.payment_record.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_record.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, Long, Integer, Integer, Byte, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, Long, Integer, Integer, Byte, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PaymentRecord.PAYMENT_RECORD.ID;
    }

    @Override
    public Field<String> field2() {
        return PaymentRecord.PAYMENT_RECORD.TRANSACTION_NO;
    }

    @Override
    public Field<Long> field3() {
        return PaymentRecord.PAYMENT_RECORD.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return PaymentRecord.PAYMENT_RECORD.DELIVERY_ADDRESS_ID;
    }

    @Override
    public Field<Integer> field5() {
        return PaymentRecord.PAYMENT_RECORD.BILLING_ADDRESS_ID;
    }

    @Override
    public Field<Byte> field6() {
        return PaymentRecord.PAYMENT_RECORD.IS_SAME_AS_DELIVERY_ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return PaymentRecord.PAYMENT_RECORD.SHIPPING_METHOD;
    }

    @Override
    public Field<String> field8() {
        return PaymentRecord.PAYMENT_RECORD.PAYMENT_TYPE;
    }

    @Override
    public Field<String> field9() {
        return PaymentRecord.PAYMENT_RECORD.PAYMENT_METHOD_ID;
    }

    @Override
    public Field<String> field10() {
        return PaymentRecord.PAYMENT_RECORD.TOKEN;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return PaymentRecord.PAYMENT_RECORD.CREATED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return PaymentRecord.PAYMENT_RECORD.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTransactionNo();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getDeliveryAddressId();
    }

    @Override
    public Integer component5() {
        return getBillingAddressId();
    }

    @Override
    public Byte component6() {
        return getIsSameAsDeliveryAddress();
    }

    @Override
    public String component7() {
        return getShippingMethod();
    }

    @Override
    public String component8() {
        return getPaymentType();
    }

    @Override
    public String component9() {
        return getPaymentMethodId();
    }

    @Override
    public String component10() {
        return getToken();
    }

    @Override
    public LocalDateTime component11() {
        return getCreated();
    }

    @Override
    public LocalDateTime component12() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTransactionNo();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getDeliveryAddressId();
    }

    @Override
    public Integer value5() {
        return getBillingAddressId();
    }

    @Override
    public Byte value6() {
        return getIsSameAsDeliveryAddress();
    }

    @Override
    public String value7() {
        return getShippingMethod();
    }

    @Override
    public String value8() {
        return getPaymentType();
    }

    @Override
    public String value9() {
        return getPaymentMethodId();
    }

    @Override
    public String value10() {
        return getToken();
    }

    @Override
    public LocalDateTime value11() {
        return getCreated();
    }

    @Override
    public LocalDateTime value12() {
        return getModified();
    }

    @Override
    public PaymentRecordRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value2(String value) {
        setTransactionNo(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value4(Integer value) {
        setDeliveryAddressId(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value5(Integer value) {
        setBillingAddressId(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value6(Byte value) {
        setIsSameAsDeliveryAddress(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value7(String value) {
        setShippingMethod(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value8(String value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value9(String value) {
        setPaymentMethodId(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value10(String value) {
        setToken(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value11(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public PaymentRecordRecord value12(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public PaymentRecordRecord values(Long value1, String value2, Long value3, Integer value4, Integer value5, Byte value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecordRecord
     */
    public PaymentRecordRecord() {
        super(PaymentRecord.PAYMENT_RECORD);
    }

    /**
     * Create a detached, initialised PaymentRecordRecord
     */
    public PaymentRecordRecord(Long id, String transactionNo, Long userId, Integer deliveryAddressId, Integer billingAddressId, Byte isSameAsDeliveryAddress, String shippingMethod, String paymentType, String paymentMethodId, String token, LocalDateTime created, LocalDateTime modified) {
        super(PaymentRecord.PAYMENT_RECORD);

        set(0, id);
        set(1, transactionNo);
        set(2, userId);
        set(3, deliveryAddressId);
        set(4, billingAddressId);
        set(5, isSameAsDeliveryAddress);
        set(6, shippingMethod);
        set(7, paymentType);
        set(8, paymentMethodId);
        set(9, token);
        set(10, created);
        set(11, modified);
    }
}
