/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.PaymentInvoice;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 支付发票表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentInvoiceRecord extends UpdatableRecordImpl<PaymentInvoiceRecord> implements Record15<Long, String, Long, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer, String, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1623655796;

    /**
     * Setter for <code>etrade_goods.payment_invoice.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.pay_no</code>. 支付编号
     */
    public void setPayNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.pay_no</code>. 支付编号
     */
    public String getPayNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.user_id</code>. 买家用户id
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.user_id</code>. 买家用户id
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.title</code>. 支付抬头
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.title</code>. 支付抬头
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.other_fees</code>. 其他系统所得费用
     */
    public void setOtherFees(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.other_fees</code>. 其他系统所得费用
     */
    public BigDecimal getOtherFees() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.tax</code>. 商品税或者叫佣金，系统所得费用
     */
    public void setTax(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.tax</code>. 商品税或者叫佣金，系统所得费用
     */
    public BigDecimal getTax() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.amount</code>. 商家所得费用，如商品费用
     */
    public void setAmount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.amount</code>. 商家所得费用，如商品费用
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.payment_method_id</code>. 买家支付方式id
     */
    public void setPaymentMethodId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.payment_method_id</code>. 买家支付方式id
     */
    public String getPaymentMethodId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.payment_type</code>. 买家支付类型
     */
    public void setPaymentType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.payment_type</code>. 买家支付类型
     */
    public String getPaymentType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.billing_address_id</code>. 账单地址id
     */
    public void setBillingAddressId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.billing_address_id</code>. 账单地址id
     */
    public Integer getBillingAddressId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.invoice_id</code>. 支付成功后发票id
     */
    public void setInvoiceId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.invoice_id</code>. 支付成功后发票id
     */
    public String getInvoiceId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.payment_card_id</code>. 如果付款方式是card，支付卡号id
     */
    public void setPaymentCardId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.payment_card_id</code>. 如果付款方式是card，支付卡号id
     */
    public Integer getPaymentCardId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.payment_seller_id</code>. 商家支付账号id
     */
    public void setPaymentSellerId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.payment_seller_id</code>. 商家支付账号id
     */
    public String getPaymentSellerId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>etrade_goods.payment_invoice.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_invoice.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, Long, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer, String, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, Long, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer, String, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PaymentInvoice.PAYMENT_INVOICE.ID;
    }

    @Override
    public Field<String> field2() {
        return PaymentInvoice.PAYMENT_INVOICE.PAY_NO;
    }

    @Override
    public Field<Long> field3() {
        return PaymentInvoice.PAYMENT_INVOICE.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return PaymentInvoice.PAYMENT_INVOICE.TITLE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return PaymentInvoice.PAYMENT_INVOICE.OTHER_FEES;
    }

    @Override
    public Field<BigDecimal> field6() {
        return PaymentInvoice.PAYMENT_INVOICE.TAX;
    }

    @Override
    public Field<BigDecimal> field7() {
        return PaymentInvoice.PAYMENT_INVOICE.AMOUNT;
    }

    @Override
    public Field<String> field8() {
        return PaymentInvoice.PAYMENT_INVOICE.PAYMENT_METHOD_ID;
    }

    @Override
    public Field<String> field9() {
        return PaymentInvoice.PAYMENT_INVOICE.PAYMENT_TYPE;
    }

    @Override
    public Field<Integer> field10() {
        return PaymentInvoice.PAYMENT_INVOICE.BILLING_ADDRESS_ID;
    }

    @Override
    public Field<String> field11() {
        return PaymentInvoice.PAYMENT_INVOICE.INVOICE_ID;
    }

    @Override
    public Field<Integer> field12() {
        return PaymentInvoice.PAYMENT_INVOICE.PAYMENT_CARD_ID;
    }

    @Override
    public Field<String> field13() {
        return PaymentInvoice.PAYMENT_INVOICE.PAYMENT_SELLER_ID;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return PaymentInvoice.PAYMENT_INVOICE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return PaymentInvoice.PAYMENT_INVOICE.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPayNo();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public BigDecimal component5() {
        return getOtherFees();
    }

    @Override
    public BigDecimal component6() {
        return getTax();
    }

    @Override
    public BigDecimal component7() {
        return getAmount();
    }

    @Override
    public String component8() {
        return getPaymentMethodId();
    }

    @Override
    public String component9() {
        return getPaymentType();
    }

    @Override
    public Integer component10() {
        return getBillingAddressId();
    }

    @Override
    public String component11() {
        return getInvoiceId();
    }

    @Override
    public Integer component12() {
        return getPaymentCardId();
    }

    @Override
    public String component13() {
        return getPaymentSellerId();
    }

    @Override
    public LocalDateTime component14() {
        return getCreated();
    }

    @Override
    public LocalDateTime component15() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPayNo();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public BigDecimal value5() {
        return getOtherFees();
    }

    @Override
    public BigDecimal value6() {
        return getTax();
    }

    @Override
    public BigDecimal value7() {
        return getAmount();
    }

    @Override
    public String value8() {
        return getPaymentMethodId();
    }

    @Override
    public String value9() {
        return getPaymentType();
    }

    @Override
    public Integer value10() {
        return getBillingAddressId();
    }

    @Override
    public String value11() {
        return getInvoiceId();
    }

    @Override
    public Integer value12() {
        return getPaymentCardId();
    }

    @Override
    public String value13() {
        return getPaymentSellerId();
    }

    @Override
    public LocalDateTime value14() {
        return getCreated();
    }

    @Override
    public LocalDateTime value15() {
        return getModified();
    }

    @Override
    public PaymentInvoiceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value2(String value) {
        setPayNo(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value5(BigDecimal value) {
        setOtherFees(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value6(BigDecimal value) {
        setTax(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value7(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value8(String value) {
        setPaymentMethodId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value9(String value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value10(Integer value) {
        setBillingAddressId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value11(String value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value12(Integer value) {
        setPaymentCardId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value13(String value) {
        setPaymentSellerId(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value14(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord value15(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public PaymentInvoiceRecord values(Long value1, String value2, Long value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, String value8, String value9, Integer value10, String value11, Integer value12, String value13, LocalDateTime value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentInvoiceRecord
     */
    public PaymentInvoiceRecord() {
        super(PaymentInvoice.PAYMENT_INVOICE);
    }

    /**
     * Create a detached, initialised PaymentInvoiceRecord
     */
    public PaymentInvoiceRecord(Long id, String payNo, Long userId, String title, BigDecimal otherFees, BigDecimal tax, BigDecimal amount, String paymentMethodId, String paymentType, Integer billingAddressId, String invoiceId, Integer paymentCardId, String paymentSellerId, LocalDateTime created, LocalDateTime modified) {
        super(PaymentInvoice.PAYMENT_INVOICE);

        set(0, id);
        set(1, payNo);
        set(2, userId);
        set(3, title);
        set(4, otherFees);
        set(5, tax);
        set(6, amount);
        set(7, paymentMethodId);
        set(8, paymentType);
        set(9, billingAddressId);
        set(10, invoiceId);
        set(11, paymentCardId);
        set(12, paymentSellerId);
        set(13, created);
        set(14, modified);
    }
}
