/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.PaymentCustomerAddress;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 账单地址/买家收货地址
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentCustomerAddressRecord extends UpdatableRecordImpl<PaymentCustomerAddressRecord> implements Record16<Integer, Long, String, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 534842036;

    /**
     * Setter for <code>etrade_goods.payment_customer_address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.user_id</code>. 系统用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.user_id</code>. 系统用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.title</code>. 标题，用来区分不同的地址
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.title</code>. 标题，用来区分不同的地址
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.first_name</code>. 名字
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.first_name</code>. 名字
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.last_name</code>. 姓氏
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.last_name</code>. 姓氏
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.phone_number</code>. 电话号码
     */
    public void setPhoneNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.phone_number</code>. 电话号码
     */
    public String getPhoneNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.address_line1</code>. 详细地址1
     */
    public void setAddressLine1(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.address_line1</code>. 详细地址1
     */
    public String getAddressLine1() {
        return (String) get(6);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.address_line2</code>. 详细地址2
     */
    public void setAddressLine2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.address_line2</code>. 详细地址2
     */
    public String getAddressLine2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.post_code</code>. 邮编
     */
    public void setPostCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.post_code</code>. 邮编
     */
    public String getPostCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.city</code>. 城市
     */
    public void setCity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.city</code>. 城市
     */
    public String getCity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.state</code>. 州/省
     */
    public void setState(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.state</code>. 州/省
     */
    public String getState() {
        return (String) get(10);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.country</code>. 国家
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.country</code>. 国家
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.is_default</code>. 是否是默认地址
     */
    public void setIsDefault(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.is_default</code>. 是否是默认地址
     */
    public Byte getIsDefault() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.type</code>. billing/delivery：账单地址/买家收货地址
     */
    public void setType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.type</code>. billing/delivery：账单地址/买家收货地址
     */
    public String getType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>etrade_goods.payment_customer_address.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>etrade_goods.payment_customer_address.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, Long, String, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, Long, String, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.ID;
    }

    @Override
    public Field<Long> field2() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.TITLE;
    }

    @Override
    public Field<String> field4() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.PHONE_NUMBER;
    }

    @Override
    public Field<String> field7() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.ADDRESS_LINE1;
    }

    @Override
    public Field<String> field8() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.ADDRESS_LINE2;
    }

    @Override
    public Field<String> field9() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.POST_CODE;
    }

    @Override
    public Field<String> field10() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.CITY;
    }

    @Override
    public Field<String> field11() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.STATE;
    }

    @Override
    public Field<String> field12() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.COUNTRY;
    }

    @Override
    public Field<Byte> field13() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.IS_DEFAULT;
    }

    @Override
    public Field<String> field14() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.TYPE;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getPhoneNumber();
    }

    @Override
    public String component7() {
        return getAddressLine1();
    }

    @Override
    public String component8() {
        return getAddressLine2();
    }

    @Override
    public String component9() {
        return getPostCode();
    }

    @Override
    public String component10() {
        return getCity();
    }

    @Override
    public String component11() {
        return getState();
    }

    @Override
    public String component12() {
        return getCountry();
    }

    @Override
    public Byte component13() {
        return getIsDefault();
    }

    @Override
    public String component14() {
        return getType();
    }

    @Override
    public LocalDateTime component15() {
        return getCreated();
    }

    @Override
    public LocalDateTime component16() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getPhoneNumber();
    }

    @Override
    public String value7() {
        return getAddressLine1();
    }

    @Override
    public String value8() {
        return getAddressLine2();
    }

    @Override
    public String value9() {
        return getPostCode();
    }

    @Override
    public String value10() {
        return getCity();
    }

    @Override
    public String value11() {
        return getState();
    }

    @Override
    public String value12() {
        return getCountry();
    }

    @Override
    public Byte value13() {
        return getIsDefault();
    }

    @Override
    public String value14() {
        return getType();
    }

    @Override
    public LocalDateTime value15() {
        return getCreated();
    }

    @Override
    public LocalDateTime value16() {
        return getModified();
    }

    @Override
    public PaymentCustomerAddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value6(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value7(String value) {
        setAddressLine1(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value8(String value) {
        setAddressLine2(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value9(String value) {
        setPostCode(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value10(String value) {
        setCity(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value11(String value) {
        setState(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value12(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value13(Byte value) {
        setIsDefault(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value14(String value) {
        setType(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value15(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord value16(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public PaymentCustomerAddressRecord values(Integer value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Byte value13, String value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentCustomerAddressRecord
     */
    public PaymentCustomerAddressRecord() {
        super(PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS);
    }

    /**
     * Create a detached, initialised PaymentCustomerAddressRecord
     */
    public PaymentCustomerAddressRecord(Integer id, Long userId, String title, String firstName, String lastName, String phoneNumber, String addressLine1, String addressLine2, String postCode, String city, String state, String country, Byte isDefault, String type, LocalDateTime created, LocalDateTime modified) {
        super(PaymentCustomerAddress.PAYMENT_CUSTOMER_ADDRESS);

        set(0, id);
        set(1, userId);
        set(2, title);
        set(3, firstName);
        set(4, lastName);
        set(5, phoneNumber);
        set(6, addressLine1);
        set(7, addressLine2);
        set(8, postCode);
        set(9, city);
        set(10, state);
        set(11, country);
        set(12, isDefault);
        set(13, type);
        set(14, created);
        set(15, modified);
    }
}
