/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.UserBrowsingHistory;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户浏览历史
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBrowsingHistoryRecord extends UpdatableRecordImpl<UserBrowsingHistoryRecord> implements Record7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1078351494;

    /**
     * Setter for <code>etrade_goods.user_browsing_history.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.goods_id</code>. 浏览商品id
     */
    public void setGoodsId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.goods_id</code>. 浏览商品id
     */
    public Long getGoodsId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.groupon_id</code>. 浏览团购券id
     */
    public void setGrouponId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.groupon_id</code>. 浏览团购券id
     */
    public Long getGrouponId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.last_browse_time</code>. 最近浏览时间
     */
    public void setLastBrowseTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.last_browse_time</code>. 最近浏览时间
     */
    public LocalDateTime getLastBrowseTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>etrade_goods.user_browsing_history.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.user_browsing_history.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.GOODS_ID;
    }

    @Override
    public Field<Long> field4() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.GROUPON_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.LAST_BROWSE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserBrowsingHistory.USER_BROWSING_HISTORY.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getGoodsId();
    }

    @Override
    public Long component4() {
        return getGrouponId();
    }

    @Override
    public LocalDateTime component5() {
        return getLastBrowseTime();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getGoodsId();
    }

    @Override
    public Long value4() {
        return getGrouponId();
    }

    @Override
    public LocalDateTime value5() {
        return getLastBrowseTime();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public UserBrowsingHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value3(Long value) {
        setGoodsId(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value4(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value5(LocalDateTime value) {
        setLastBrowseTime(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public UserBrowsingHistoryRecord values(Long value1, Long value2, Long value3, Long value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserBrowsingHistoryRecord
     */
    public UserBrowsingHistoryRecord() {
        super(UserBrowsingHistory.USER_BROWSING_HISTORY);
    }

    /**
     * Create a detached, initialised UserBrowsingHistoryRecord
     */
    public UserBrowsingHistoryRecord(Long id, Long userId, Long goodsId, Long grouponId, LocalDateTime lastBrowseTime, LocalDateTime created, LocalDateTime modified) {
        super(UserBrowsingHistory.USER_BROWSING_HISTORY);

        set(0, id);
        set(1, userId);
        set(2, goodsId);
        set(3, grouponId);
        set(4, lastBrowseTime);
        set(5, created);
        set(6, modified);
    }
}
