/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.UserProfile;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户个人偏好设置
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1259127438;

    /**
     * Setter for <code>etrade_goods.user_profile.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.key</code>. key
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.key</code>. key
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.value</code>. value
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.value</code>. value
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.comment</code>. comment
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.comment</code>. comment
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>etrade_goods.user_profile.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.user_profile.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserProfile.USER_PROFILE.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserProfile.USER_PROFILE.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserProfile.USER_PROFILE.KEY;
    }

    @Override
    public Field<String> field4() {
        return UserProfile.USER_PROFILE.VALUE;
    }

    @Override
    public Field<String> field5() {
        return UserProfile.USER_PROFILE.COMMENT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserProfile.USER_PROFILE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserProfile.USER_PROFILE.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getKey();
    }

    @Override
    public String component4() {
        return getValue();
    }

    @Override
    public String component5() {
        return getComment();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getKey();
    }

    @Override
    public String value4() {
        return getValue();
    }

    @Override
    public String value5() {
        return getComment();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public UserProfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfileRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserProfileRecord value3(String value) {
        setKey(value);
        return this;
    }

    @Override
    public UserProfileRecord value4(String value) {
        setValue(value);
        return this;
    }

    @Override
    public UserProfileRecord value5(String value) {
        setComment(value);
        return this;
    }

    @Override
    public UserProfileRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserProfileRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public UserProfileRecord values(Long value1, Long value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(Long id, Long userId, String key, String value, String comment, LocalDateTime created, LocalDateTime modified) {
        super(UserProfile.USER_PROFILE);

        set(0, id);
        set(1, userId);
        set(2, key);
        set(3, value);
        set(4, comment);
        set(5, created);
        set(6, modified);
    }
}
