/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.UserLikes;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户收藏表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLikesRecord extends UpdatableRecordImpl<UserLikesRecord> implements Record6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1998882883;

    /**
     * Setter for <code>etrade_goods.user_likes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.user_likes.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.user_likes.goods_id</code>. 商品id
     */
    public void setGoodsId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.goods_id</code>. 商品id
     */
    public Long getGoodsId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>etrade_goods.user_likes.groupon_id</code>. 团购券id
     */
    public void setGrouponId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.groupon_id</code>. 团购券id
     */
    public Long getGrouponId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>etrade_goods.user_likes.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>etrade_goods.user_likes.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.user_likes.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserLikes.USER_LIKES.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserLikes.USER_LIKES.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserLikes.USER_LIKES.GOODS_ID;
    }

    @Override
    public Field<Long> field4() {
        return UserLikes.USER_LIKES.GROUPON_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserLikes.USER_LIKES.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserLikes.USER_LIKES.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getGoodsId();
    }

    @Override
    public Long component4() {
        return getGrouponId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getGoodsId();
    }

    @Override
    public Long value4() {
        return getGrouponId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public UserLikesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserLikesRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserLikesRecord value3(Long value) {
        setGoodsId(value);
        return this;
    }

    @Override
    public UserLikesRecord value4(Long value) {
        setGrouponId(value);
        return this;
    }

    @Override
    public UserLikesRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserLikesRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public UserLikesRecord values(Long value1, Long value2, Long value3, Long value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLikesRecord
     */
    public UserLikesRecord() {
        super(UserLikes.USER_LIKES);
    }

    /**
     * Create a detached, initialised UserLikesRecord
     */
    public UserLikesRecord(Long id, Long userId, Long goodsId, Long grouponId, LocalDateTime created, LocalDateTime modified) {
        super(UserLikes.USER_LIKES);

        set(0, id);
        set(1, userId);
        set(2, goodsId);
        set(3, grouponId);
        set(4, created);
        set(5, modified);
    }
}
