/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.UserImAction;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户IM账号
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserImActionRecord extends UpdatableRecordImpl<UserImActionRecord> implements Record7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1119561307;

    /**
     * Setter for <code>etrade_goods.user_im_action.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.accid</code>. 云信账号accid
     */
    public void setAccid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.accid</code>. 云信账号accid
     */
    public String getAccid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.name</code>. 云信账号name，即e-trade app的nickname
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.name</code>. 云信账号name，即e-trade app的nickname
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.token</code>. 云信账号授权
     */
    public void setToken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.token</code>. 云信账号授权
     */
    public String getToken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>etrade_goods.user_im_action.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.user_im_action.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserImAction.USER_IM_ACTION.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserImAction.USER_IM_ACTION.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserImAction.USER_IM_ACTION.ACCID;
    }

    @Override
    public Field<String> field4() {
        return UserImAction.USER_IM_ACTION.NAME;
    }

    @Override
    public Field<String> field5() {
        return UserImAction.USER_IM_ACTION.TOKEN;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserImAction.USER_IM_ACTION.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserImAction.USER_IM_ACTION.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getAccid();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getToken();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getAccid();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getToken();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public UserImActionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserImActionRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserImActionRecord value3(String value) {
        setAccid(value);
        return this;
    }

    @Override
    public UserImActionRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserImActionRecord value5(String value) {
        setToken(value);
        return this;
    }

    @Override
    public UserImActionRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserImActionRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public UserImActionRecord values(Long value1, Long value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserImActionRecord
     */
    public UserImActionRecord() {
        super(UserImAction.USER_IM_ACTION);
    }

    /**
     * Create a detached, initialised UserImActionRecord
     */
    public UserImActionRecord(Long id, Long userId, String accid, String name, String token, LocalDateTime created, LocalDateTime modified) {
        super(UserImAction.USER_IM_ACTION);

        set(0, id);
        set(1, userId);
        set(2, accid);
        set(3, name);
        set(4, token);
        set(5, created);
        set(6, modified);
    }
}
