/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables.records;


import com.etrade.puggo.db.tables.User;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 个人信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record21<Long, String, Byte, String, String, String, String, LocalDateTime, LocalDate, LocalDate, Byte, String, String, String, String, BigDecimal, String, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1542329199;

    /**
     * Setter for <code>etrade_goods.user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>etrade_goods.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>etrade_goods.user.nickname</code>. 用户昵称
     */
    public void setNickname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>etrade_goods.user.nickname</code>. 用户昵称
     */
    public String getNickname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>etrade_goods.user.gender</code>. 性别，0男 1女 2其他
     */
    public void setGender(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>etrade_goods.user.gender</code>. 性别，0男 1女 2其他
     */
    public Byte getGender() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>etrade_goods.user.avatar</code>. 头像
     */
    public void setAvatar(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>etrade_goods.user.avatar</code>. 头像
     */
    public String getAvatar() {
        return (String) get(3);
    }

    /**
     * Setter for <code>etrade_goods.user.introduction</code>. 简介
     */
    public void setIntroduction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>etrade_goods.user.introduction</code>. 简介
     */
    public String getIntroduction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>etrade_goods.user.email</code>. 电子邮箱
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>etrade_goods.user.email</code>. 电子邮箱
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>etrade_goods.user.phone</code>. 电话号码
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>etrade_goods.user.phone</code>. 电话号码
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>etrade_goods.user.nickname_last_time</code>. 昵称最后修改日期，昵称修改有频率限制
     */
    public void setNicknameLastTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>etrade_goods.user.nickname_last_time</code>. 昵称最后修改日期，昵称修改有频率限制
     */
    public LocalDateTime getNicknameLastTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>etrade_goods.user.birthdate</code>. 出生日期
     */
    public void setBirthdate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>etrade_goods.user.birthdate</code>. 出生日期
     */
    public LocalDate getBirthdate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>etrade_goods.user.join_date</code>. 注册日期
     */
    public void setJoinDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>etrade_goods.user.join_date</code>. 注册日期
     */
    public LocalDate getJoinDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>etrade_goods.user.deleted</code>. 是否弃用, 1 : 废弃，0 : 正常
     */
    public void setDeleted(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>etrade_goods.user.deleted</code>. 是否弃用, 1 : 废弃，0 : 正常
     */
    public Byte getDeleted() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>etrade_goods.user.country</code>. 用户所在国家
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>etrade_goods.user.country</code>. 用户所在国家
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>etrade_goods.user.province</code>. 用户所在省份/州
     */
    public void setProvince(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>etrade_goods.user.province</code>. 用户所在省份/州
     */
    public String getProvince() {
        return (String) get(12);
    }

    /**
     * Setter for <code>etrade_goods.user.city</code>. 用户所在城市
     */
    public void setCity(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>etrade_goods.user.city</code>. 用户所在城市
     */
    public String getCity() {
        return (String) get(13);
    }

    /**
     * Setter for <code>etrade_goods.user.district</code>. 用户所在区域/县
     */
    public void setDistrict(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>etrade_goods.user.district</code>. 用户所在区域/县
     */
    public String getDistrict() {
        return (String) get(14);
    }

    /**
     * Setter for <code>etrade_goods.user.credit_rating</code>. 信誉等级：1-5 数字越大信誉越好
     */
    public void setCreditRating(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>etrade_goods.user.credit_rating</code>. 信誉等级：1-5 数字越大信誉越好
     */
    public BigDecimal getCreditRating() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>etrade_goods.user.user_role</code>. 用户角色
     */
    public void setUserRole(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>etrade_goods.user.user_role</code>. 用户角色
     */
    public String getUserRole() {
        return (String) get(16);
    }

    /**
     * Setter for <code>etrade_goods.user.is_verified</code>. 是否认证: 1认证 0未认证
     */
    public void setIsVerified(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>etrade_goods.user.is_verified</code>. 是否认证: 1认证 0未认证
     */
    public Byte getIsVerified() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>etrade_goods.user.payment_customer_id</code>. 支付账户id
     */
    public void setPaymentCustomerId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>etrade_goods.user.payment_customer_id</code>. 支付账户id
     */
    public String getPaymentCustomerId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>etrade_goods.user.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>etrade_goods.user.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>etrade_goods.user.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>etrade_goods.user.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Long, String, Byte, String, String, String, String, LocalDateTime, LocalDate, LocalDate, Byte, String, String, String, String, BigDecimal, String, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Long, String, Byte, String, String, String, String, LocalDateTime, LocalDate, LocalDate, Byte, String, String, String, String, BigDecimal, String, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NICKNAME;
    }

    @Override
    public Field<Byte> field3() {
        return User.USER.GENDER;
    }

    @Override
    public Field<String> field4() {
        return User.USER.AVATAR;
    }

    @Override
    public Field<String> field5() {
        return User.USER.INTRODUCTION;
    }

    @Override
    public Field<String> field6() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return User.USER.PHONE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return User.USER.NICKNAME_LAST_TIME;
    }

    @Override
    public Field<LocalDate> field9() {
        return User.USER.BIRTHDATE;
    }

    @Override
    public Field<LocalDate> field10() {
        return User.USER.JOIN_DATE;
    }

    @Override
    public Field<Byte> field11() {
        return User.USER.DELETED;
    }

    @Override
    public Field<String> field12() {
        return User.USER.COUNTRY;
    }

    @Override
    public Field<String> field13() {
        return User.USER.PROVINCE;
    }

    @Override
    public Field<String> field14() {
        return User.USER.CITY;
    }

    @Override
    public Field<String> field15() {
        return User.USER.DISTRICT;
    }

    @Override
    public Field<BigDecimal> field16() {
        return User.USER.CREDIT_RATING;
    }

    @Override
    public Field<String> field17() {
        return User.USER.USER_ROLE;
    }

    @Override
    public Field<Byte> field18() {
        return User.USER.IS_VERIFIED;
    }

    @Override
    public Field<String> field19() {
        return User.USER.PAYMENT_CUSTOMER_ID;
    }

    @Override
    public Field<LocalDateTime> field20() {
        return User.USER.CREATED;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return User.USER.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNickname();
    }

    @Override
    public Byte component3() {
        return getGender();
    }

    @Override
    public String component4() {
        return getAvatar();
    }

    @Override
    public String component5() {
        return getIntroduction();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public LocalDateTime component8() {
        return getNicknameLastTime();
    }

    @Override
    public LocalDate component9() {
        return getBirthdate();
    }

    @Override
    public LocalDate component10() {
        return getJoinDate();
    }

    @Override
    public Byte component11() {
        return getDeleted();
    }

    @Override
    public String component12() {
        return getCountry();
    }

    @Override
    public String component13() {
        return getProvince();
    }

    @Override
    public String component14() {
        return getCity();
    }

    @Override
    public String component15() {
        return getDistrict();
    }

    @Override
    public BigDecimal component16() {
        return getCreditRating();
    }

    @Override
    public String component17() {
        return getUserRole();
    }

    @Override
    public Byte component18() {
        return getIsVerified();
    }

    @Override
    public String component19() {
        return getPaymentCustomerId();
    }

    @Override
    public LocalDateTime component20() {
        return getCreated();
    }

    @Override
    public LocalDateTime component21() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNickname();
    }

    @Override
    public Byte value3() {
        return getGender();
    }

    @Override
    public String value4() {
        return getAvatar();
    }

    @Override
    public String value5() {
        return getIntroduction();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public LocalDateTime value8() {
        return getNicknameLastTime();
    }

    @Override
    public LocalDate value9() {
        return getBirthdate();
    }

    @Override
    public LocalDate value10() {
        return getJoinDate();
    }

    @Override
    public Byte value11() {
        return getDeleted();
    }

    @Override
    public String value12() {
        return getCountry();
    }

    @Override
    public String value13() {
        return getProvince();
    }

    @Override
    public String value14() {
        return getCity();
    }

    @Override
    public String value15() {
        return getDistrict();
    }

    @Override
    public BigDecimal value16() {
        return getCreditRating();
    }

    @Override
    public String value17() {
        return getUserRole();
    }

    @Override
    public Byte value18() {
        return getIsVerified();
    }

    @Override
    public String value19() {
        return getPaymentCustomerId();
    }

    @Override
    public LocalDateTime value20() {
        return getCreated();
    }

    @Override
    public LocalDateTime value21() {
        return getModified();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public UserRecord value3(Byte value) {
        setGender(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setIntroduction(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UserRecord value8(LocalDateTime value) {
        setNicknameLastTime(value);
        return this;
    }

    @Override
    public UserRecord value9(LocalDate value) {
        setBirthdate(value);
        return this;
    }

    @Override
    public UserRecord value10(LocalDate value) {
        setJoinDate(value);
        return this;
    }

    @Override
    public UserRecord value11(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public UserRecord value12(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public UserRecord value13(String value) {
        setProvince(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UserRecord value15(String value) {
        setDistrict(value);
        return this;
    }

    @Override
    public UserRecord value16(BigDecimal value) {
        setCreditRating(value);
        return this;
    }

    @Override
    public UserRecord value17(String value) {
        setUserRole(value);
        return this;
    }

    @Override
    public UserRecord value18(Byte value) {
        setIsVerified(value);
        return this;
    }

    @Override
    public UserRecord value19(String value) {
        setPaymentCustomerId(value);
        return this;
    }

    @Override
    public UserRecord value20(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public UserRecord value21(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, Byte value3, String value4, String value5, String value6, String value7, LocalDateTime value8, LocalDate value9, LocalDate value10, Byte value11, String value12, String value13, String value14, String value15, BigDecimal value16, String value17, Byte value18, String value19, LocalDateTime value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String nickname, Byte gender, String avatar, String introduction, String email, String phone, LocalDateTime nicknameLastTime, LocalDate birthdate, LocalDate joinDate, Byte deleted, String country, String province, String city, String district, BigDecimal creditRating, String userRole, Byte isVerified, String paymentCustomerId, LocalDateTime created, LocalDateTime modified) {
        super(User.USER);

        set(0, id);
        set(1, nickname);
        set(2, gender);
        set(3, avatar);
        set(4, introduction);
        set(5, email);
        set(6, phone);
        set(7, nicknameLastTime);
        set(8, birthdate);
        set(9, joinDate);
        set(10, deleted);
        set(11, country);
        set(12, province);
        set(13, city);
        set(14, district);
        set(15, creditRating);
        set(16, userRole);
        set(17, isVerified);
        set(18, paymentCustomerId);
        set(19, created);
        set(20, modified);
    }
}
