/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables;


import com.etrade.puggo.db.EtradeGoods;
import com.etrade.puggo.db.Indexes;
import com.etrade.puggo.db.Keys;
import com.etrade.puggo.db.tables.records.AiBrandListRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * AI鉴定品牌
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiBrandList extends TableImpl<AiBrandListRecord> {

    private static final long serialVersionUID = -491232116;

    /**
     * The reference instance of <code>etrade_goods.ai_brand_list</code>
     */
    public static final AiBrandList AI_BRAND_LIST = new AiBrandList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiBrandListRecord> getRecordType() {
        return AiBrandListRecord.class;
    }

    /**
     * The column <code>etrade_goods.ai_brand_list.id</code>. 品牌id，值取自接口返回
     */
    public final TableField<AiBrandListRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "品牌id，值取自接口返回");

    /**
     * The column <code>etrade_goods.ai_brand_list.kind_id</code>. 品类id
     */
    public final TableField<AiBrandListRecord, Integer> KIND_ID = createField(DSL.name("kind_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "品类id");

    /**
     * The column <code>etrade_goods.ai_brand_list.name</code>. 品牌名
     */
    public final TableField<AiBrandListRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "品牌名");

    /**
     * The column <code>etrade_goods.ai_brand_list.is_related</code>. 是否关联鉴定点（若为true，则该品牌直接跳转至鉴定点信息）
     */
    public final TableField<AiBrandListRecord, Byte> IS_RELATED = createField(DSL.name("is_related"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否关联鉴定点（若为true，则该品牌直接跳转至鉴定点信息）");

    /**
     * The column <code>etrade_goods.ai_brand_list.example_img</code>. 品牌示意图
     */
    public final TableField<AiBrandListRecord, String> EXAMPLE_IMG = createField(DSL.name("example_img"), org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "品牌示意图");

    /**
     * The column <code>etrade_goods.ai_brand_list.is_show</code>. 是否展示
     */
    public final TableField<AiBrandListRecord, Byte> IS_SHOW = createField(DSL.name("is_show"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否展示");

    /**
     * The column <code>etrade_goods.ai_brand_list.created</code>.
     */
    public final TableField<AiBrandListRecord, LocalDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.ai_brand_list.modified</code>.
     */
    public final TableField<AiBrandListRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>etrade_goods.ai_brand_list</code> table reference
     */
    public AiBrandList() {
        this(DSL.name("ai_brand_list"), null);
    }

    /**
     * Create an aliased <code>etrade_goods.ai_brand_list</code> table reference
     */
    public AiBrandList(String alias) {
        this(DSL.name(alias), AI_BRAND_LIST);
    }

    /**
     * Create an aliased <code>etrade_goods.ai_brand_list</code> table reference
     */
    public AiBrandList(Name alias) {
        this(alias, AI_BRAND_LIST);
    }

    private AiBrandList(Name alias, Table<AiBrandListRecord> aliased) {
        this(alias, aliased, null);
    }

    private AiBrandList(Name alias, Table<AiBrandListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("AI鉴定品牌"));
    }

    public <O extends Record> AiBrandList(Table<O> child, ForeignKey<O, AiBrandListRecord> key) {
        super(child, key, AI_BRAND_LIST);
    }

    @Override
    public Schema getSchema() {
        return EtradeGoods.ETRADE_GOODS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AI_BRAND_LIST_PRIMARY);
    }

    @Override
    public UniqueKey<AiBrandListRecord> getPrimaryKey() {
        return Keys.KEY_AI_BRAND_LIST_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiBrandListRecord>> getKeys() {
        return Arrays.<UniqueKey<AiBrandListRecord>>asList(Keys.KEY_AI_BRAND_LIST_PRIMARY);
    }

    @Override
    public AiBrandList as(String alias) {
        return new AiBrandList(DSL.name(alias), this);
    }

    @Override
    public AiBrandList as(Name alias) {
        return new AiBrandList(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiBrandList rename(String name) {
        return new AiBrandList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiBrandList rename(Name name) {
        return new AiBrandList(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, Byte, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
