/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables;


import com.etrade.puggo.db.EtradeGoods;
import com.etrade.puggo.db.Indexes;
import com.etrade.puggo.db.Keys;
import com.etrade.puggo.db.tables.records.GrouponCouponRuleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 团购优惠券使用规则
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponRule extends TableImpl<GrouponCouponRuleRecord> {

    private static final long serialVersionUID = 1465119344;

    /**
     * The reference instance of <code>etrade_goods.groupon_coupon_rule</code>
     */
    public static final GrouponCouponRule GROUPON_COUPON_RULE = new GrouponCouponRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrouponCouponRuleRecord> getRecordType() {
        return GrouponCouponRuleRecord.class;
    }

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.id</code>.
     */
    public final TableField<GrouponCouponRuleRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.groupon_id</code>. 团购券id
     */
    public final TableField<GrouponCouponRuleRecord, Long> GROUPON_ID = createField(DSL.name("groupon_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "团购券id");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.service_time_interval</code>. 有效时间区间：&lt;= and &lt;=BETWEEN; &gt;=GE; &lt;=LE
     */
    public final TableField<GrouponCouponRuleRecord, String> SERVICE_TIME_INTERVAL = createField(DSL.name("service_time_interval"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "有效时间区间：<= and <=BETWEEN; >=GE; <=LE");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.service_time_unit</code>. 有效时间单位: DATE; WEEK
     */
    public final TableField<GrouponCouponRuleRecord, String> SERVICE_TIME_UNIT = createField(DSL.name("service_time_unit"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "有效时间单位: DATE; WEEK");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.service_time_start</code>. 有效时间开始
     */
    public final TableField<GrouponCouponRuleRecord, String> SERVICE_TIME_START = createField(DSL.name("service_time_start"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "有效时间开始");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.service_time_end</code>. 有效时间截止
     */
    public final TableField<GrouponCouponRuleRecord, String> SERVICE_TIME_END = createField(DSL.name("service_time_end"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "有效时间截止");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.min_reply_hours</code>. 最小回复时间
     */
    public final TableField<GrouponCouponRuleRecord, Byte> MIN_REPLY_HOURS = createField(DSL.name("min_reply_hours"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "最小回复时间");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.is_allow_cancel</code>. 是否允许取消, 值为1时允许
     */
    public final TableField<GrouponCouponRuleRecord, Byte> IS_ALLOW_CANCEL = createField(DSL.name("is_allow_cancel"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否允许取消, 值为1时允许");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.applicable_brand</code>. 适用的品牌
     */
    public final TableField<GrouponCouponRuleRecord, String> APPLICABLE_BRAND = createField(DSL.name("applicable_brand"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "适用的品牌");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.applicable_shop</code>. 适用的门店
     */
    public final TableField<GrouponCouponRuleRecord, String> APPLICABLE_SHOP = createField(DSL.name("applicable_shop"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "适用的门店");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.shop_address</code>. 适用门店地址
     */
    public final TableField<GrouponCouponRuleRecord, String> SHOP_ADDRESS = createField(DSL.name("shop_address"), org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "适用门店地址");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.shop_arrival_method</code>. 门店到达方式
     */
    public final TableField<GrouponCouponRuleRecord, String> SHOP_ARRIVAL_METHOD = createField(DSL.name("shop_arrival_method"), org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "门店到达方式");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.limit_number</code>. 限制订购数量
     */
    public final TableField<GrouponCouponRuleRecord, Integer> LIMIT_NUMBER = createField(DSL.name("limit_number"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "限制订购数量");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.created</code>.
     */
    public final TableField<GrouponCouponRuleRecord, LocalDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.modified</code>.
     */
    public final TableField<GrouponCouponRuleRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.groupon_coupon_rule.effective_days</code>. 有效天数
     */
    public final TableField<GrouponCouponRuleRecord, Integer> EFFECTIVE_DAYS = createField(DSL.name("effective_days"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "有效天数");

    /**
     * Create a <code>etrade_goods.groupon_coupon_rule</code> table reference
     */
    public GrouponCouponRule() {
        this(DSL.name("groupon_coupon_rule"), null);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_coupon_rule</code> table reference
     */
    public GrouponCouponRule(String alias) {
        this(DSL.name(alias), GROUPON_COUPON_RULE);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_coupon_rule</code> table reference
     */
    public GrouponCouponRule(Name alias) {
        this(alias, GROUPON_COUPON_RULE);
    }

    private GrouponCouponRule(Name alias, Table<GrouponCouponRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrouponCouponRule(Name alias, Table<GrouponCouponRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("团购优惠券使用规则"));
    }

    public <O extends Record> GrouponCouponRule(Table<O> child, ForeignKey<O, GrouponCouponRuleRecord> key) {
        super(child, key, GROUPON_COUPON_RULE);
    }

    @Override
    public Schema getSchema() {
        return EtradeGoods.ETRADE_GOODS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUPON_COUPON_RULE_IDX_GROUPON_ID, Indexes.GROUPON_COUPON_RULE_PRIMARY);
    }

    @Override
    public Identity<GrouponCouponRuleRecord, Long> getIdentity() {
        return Keys.IDENTITY_GROUPON_COUPON_RULE;
    }

    @Override
    public UniqueKey<GrouponCouponRuleRecord> getPrimaryKey() {
        return Keys.KEY_GROUPON_COUPON_RULE_PRIMARY;
    }

    @Override
    public List<UniqueKey<GrouponCouponRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<GrouponCouponRuleRecord>>asList(Keys.KEY_GROUPON_COUPON_RULE_PRIMARY);
    }

    @Override
    public GrouponCouponRule as(String alias) {
        return new GrouponCouponRule(DSL.name(alias), this);
    }

    @Override
    public GrouponCouponRule as(Name alias) {
        return new GrouponCouponRule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponCouponRule rename(String name) {
        return new GrouponCouponRule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponCouponRule rename(Name name) {
        return new GrouponCouponRule(name, null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, String, String, String, String, Byte, Byte, String, String, String, String, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }
}
