/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables;


import com.etrade.puggo.db.EtradeGoods;
import com.etrade.puggo.db.Indexes;
import com.etrade.puggo.db.Keys;
import com.etrade.puggo.db.tables.records.GrouponClassRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 团购分类
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponClass extends TableImpl<GrouponClassRecord> {

    private static final long serialVersionUID = 1402698876;

    /**
     * The reference instance of <code>etrade_goods.groupon_class</code>
     */
    public static final GrouponClass GROUPON_CLASS = new GrouponClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrouponClassRecord> getRecordType() {
        return GrouponClassRecord.class;
    }

    /**
     * The column <code>etrade_goods.groupon_class.id</code>.
     */
    public final TableField<GrouponClassRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>etrade_goods.groupon_class.class_name</code>. 级别名称
     */
    public final TableField<GrouponClassRecord, String> CLASS_NAME = createField(DSL.name("class_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "级别名称");

    /**
     * The column <code>etrade_goods.groupon_class.class_path</code>. 级别path,用于搜索,例如衣服id为1,衣服下的二级T恤id为14,则T恤path为1:14
     */
    public final TableField<GrouponClassRecord, String> CLASS_PATH = createField(DSL.name("class_path"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "级别path,用于搜索,例如衣服id为1,衣服下的二级T恤id为14,则T恤path为1:14");

    /**
     * The column <code>etrade_goods.groupon_class.class_level</code>. 级别,从1到n,数字越大分类越精细
     */
    public final TableField<GrouponClassRecord, Byte> CLASS_LEVEL = createField(DSL.name("class_level"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "级别,从1到n,数字越大分类越精细");

    /**
     * The column <code>etrade_goods.groupon_class.created</code>.
     */
    public final TableField<GrouponClassRecord, LocalDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.groupon_class.modified</code>.
     */
    public final TableField<GrouponClassRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.groupon_class.icon_id</code>. icon
     */
    public final TableField<GrouponClassRecord, Long> ICON_ID = createField(DSL.name("icon_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "icon");

    /**
     * Create a <code>etrade_goods.groupon_class</code> table reference
     */
    public GrouponClass() {
        this(DSL.name("groupon_class"), null);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_class</code> table reference
     */
    public GrouponClass(String alias) {
        this(DSL.name(alias), GROUPON_CLASS);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_class</code> table reference
     */
    public GrouponClass(Name alias) {
        this(alias, GROUPON_CLASS);
    }

    private GrouponClass(Name alias, Table<GrouponClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrouponClass(Name alias, Table<GrouponClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("团购分类"));
    }

    public <O extends Record> GrouponClass(Table<O> child, ForeignKey<O, GrouponClassRecord> key) {
        super(child, key, GROUPON_CLASS);
    }

    @Override
    public Schema getSchema() {
        return EtradeGoods.ETRADE_GOODS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUPON_CLASS_IDX_CLASS_PATH, Indexes.GROUPON_CLASS_PRIMARY);
    }

    @Override
    public Identity<GrouponClassRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GROUPON_CLASS;
    }

    @Override
    public UniqueKey<GrouponClassRecord> getPrimaryKey() {
        return Keys.KEY_GROUPON_CLASS_PRIMARY;
    }

    @Override
    public List<UniqueKey<GrouponClassRecord>> getKeys() {
        return Arrays.<UniqueKey<GrouponClassRecord>>asList(Keys.KEY_GROUPON_CLASS_PRIMARY);
    }

    @Override
    public GrouponClass as(String alias) {
        return new GrouponClass(DSL.name(alias), this);
    }

    @Override
    public GrouponClass as(Name alias) {
        return new GrouponClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponClass rename(String name) {
        return new GrouponClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponClass rename(Name name) {
        return new GrouponClass(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Byte, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
