/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables;


import com.etrade.puggo.db.EtradeGoods;
import com.etrade.puggo.db.Indexes;
import com.etrade.puggo.db.Keys;
import com.etrade.puggo.db.tables.records.GrouponCouponPictureRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 团购券图片
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrouponCouponPicture extends TableImpl<GrouponCouponPictureRecord> {

    private static final long serialVersionUID = -368888075;

    /**
     * The reference instance of <code>etrade_goods.groupon_coupon_picture</code>
     */
    public static final GrouponCouponPicture GROUPON_COUPON_PICTURE = new GrouponCouponPicture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrouponCouponPictureRecord> getRecordType() {
        return GrouponCouponPictureRecord.class;
    }

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.id</code>.
     */
    public final TableField<GrouponCouponPictureRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.groupon_id</code>. 团购券id
     */
    public final TableField<GrouponCouponPictureRecord, Long> GROUPON_ID = createField(DSL.name("groupon_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "团购券id");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.url</code>. 对象存储地址
     */
    public final TableField<GrouponCouponPictureRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "对象存储地址");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.key</code>. 对象存储key
     */
    public final TableField<GrouponCouponPictureRecord, String> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "对象存储key");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.version_id</code>. 对象存储版本号
     */
    public final TableField<GrouponCouponPictureRecord, String> VERSION_ID = createField(DSL.name("version_id"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "对象存储版本号");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.is_main</code>. 是否商品主图：1是
     */
    public final TableField<GrouponCouponPictureRecord, Byte> IS_MAIN = createField(DSL.name("is_main"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否商品主图：1是");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.deleted</code>. 是否弃用, 1 : 废弃，0 : 正常
     */
    public final TableField<GrouponCouponPictureRecord, Byte> DELETED = createField(DSL.name("deleted"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否弃用, 1 : 废弃，0 : 正常");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.created</code>.
     */
    public final TableField<GrouponCouponPictureRecord, LocalDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.groupon_coupon_picture.is_icon</code>. 是否是icon：值为1时是icon
     */
    public final TableField<GrouponCouponPictureRecord, Byte> IS_ICON = createField(DSL.name("is_icon"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否是icon：值为1时是icon");

    /**
     * Create a <code>etrade_goods.groupon_coupon_picture</code> table reference
     */
    public GrouponCouponPicture() {
        this(DSL.name("groupon_coupon_picture"), null);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_coupon_picture</code> table reference
     */
    public GrouponCouponPicture(String alias) {
        this(DSL.name(alias), GROUPON_COUPON_PICTURE);
    }

    /**
     * Create an aliased <code>etrade_goods.groupon_coupon_picture</code> table reference
     */
    public GrouponCouponPicture(Name alias) {
        this(alias, GROUPON_COUPON_PICTURE);
    }

    private GrouponCouponPicture(Name alias, Table<GrouponCouponPictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrouponCouponPicture(Name alias, Table<GrouponCouponPictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("团购券图片"));
    }

    public <O extends Record> GrouponCouponPicture(Table<O> child, ForeignKey<O, GrouponCouponPictureRecord> key) {
        super(child, key, GROUPON_COUPON_PICTURE);
    }

    @Override
    public Schema getSchema() {
        return EtradeGoods.ETRADE_GOODS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUPON_COUPON_PICTURE_IDX_GROUPON_ID, Indexes.GROUPON_COUPON_PICTURE_IDX_KEY, Indexes.GROUPON_COUPON_PICTURE_PRIMARY);
    }

    @Override
    public Identity<GrouponCouponPictureRecord, Long> getIdentity() {
        return Keys.IDENTITY_GROUPON_COUPON_PICTURE;
    }

    @Override
    public UniqueKey<GrouponCouponPictureRecord> getPrimaryKey() {
        return Keys.KEY_GROUPON_COUPON_PICTURE_PRIMARY;
    }

    @Override
    public List<UniqueKey<GrouponCouponPictureRecord>> getKeys() {
        return Arrays.<UniqueKey<GrouponCouponPictureRecord>>asList(Keys.KEY_GROUPON_COUPON_PICTURE_PRIMARY);
    }

    @Override
    public GrouponCouponPicture as(String alias) {
        return new GrouponCouponPicture(DSL.name(alias), this);
    }

    @Override
    public GrouponCouponPicture as(Name alias) {
        return new GrouponCouponPicture(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponCouponPicture rename(String name) {
        return new GrouponCouponPicture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GrouponCouponPicture rename(Name name) {
        return new GrouponCouponPicture(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, Byte, Byte, LocalDateTime, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
