/*
 * This file is generated by jOOQ.
 */
package com.etrade.puggo.db.tables;


import com.etrade.puggo.db.EtradeGoods;
import com.etrade.puggo.db.Indexes;
import com.etrade.puggo.db.Keys;
import com.etrade.puggo.db.tables.records.UserFansRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 用户粉丝表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFans extends TableImpl<UserFansRecord> {

    private static final long serialVersionUID = 180036921;

    /**
     * The reference instance of <code>etrade_goods.user_fans</code>
     */
    public static final UserFans USER_FANS = new UserFans();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserFansRecord> getRecordType() {
        return UserFansRecord.class;
    }

    /**
     * The column <code>etrade_goods.user_fans.id</code>.
     */
    public final TableField<UserFansRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>etrade_goods.user_fans.user_id</code>. 用户id
     */
    public final TableField<UserFansRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "用户id");

    /**
     * The column <code>etrade_goods.user_fans.fans_user_id</code>. 粉丝用户id
     */
    public final TableField<UserFansRecord, Long> FANS_USER_ID = createField(DSL.name("fans_user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "粉丝用户id");

    /**
     * The column <code>etrade_goods.user_fans.created</code>.
     */
    public final TableField<UserFansRecord, LocalDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>etrade_goods.user_fans.modified</code>.
     */
    public final TableField<UserFansRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>etrade_goods.user_fans</code> table reference
     */
    public UserFans() {
        this(DSL.name("user_fans"), null);
    }

    /**
     * Create an aliased <code>etrade_goods.user_fans</code> table reference
     */
    public UserFans(String alias) {
        this(DSL.name(alias), USER_FANS);
    }

    /**
     * Create an aliased <code>etrade_goods.user_fans</code> table reference
     */
    public UserFans(Name alias) {
        this(alias, USER_FANS);
    }

    private UserFans(Name alias, Table<UserFansRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserFans(Name alias, Table<UserFansRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户粉丝表"));
    }

    public <O extends Record> UserFans(Table<O> child, ForeignKey<O, UserFansRecord> key) {
        super(child, key, USER_FANS);
    }

    @Override
    public Schema getSchema() {
        return EtradeGoods.ETRADE_GOODS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_FANS_IDX_FANSUSERID, Indexes.USER_FANS_PRIMARY, Indexes.USER_FANS_UK_USERID_FANSUSERID);
    }

    @Override
    public Identity<UserFansRecord, Long> getIdentity() {
        return Keys.IDENTITY_USER_FANS;
    }

    @Override
    public UniqueKey<UserFansRecord> getPrimaryKey() {
        return Keys.KEY_USER_FANS_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserFansRecord>> getKeys() {
        return Arrays.<UniqueKey<UserFansRecord>>asList(Keys.KEY_USER_FANS_PRIMARY, Keys.KEY_USER_FANS_UK_USERID_FANSUSERID);
    }

    @Override
    public UserFans as(String alias) {
        return new UserFans(DSL.name(alias), this);
    }

    @Override
    public UserFans as(Name alias) {
        return new UserFans(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFans rename(String name) {
        return new UserFans(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFans rename(Name name) {
        return new UserFans(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
